---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: home-postgres
spec:
  teamId: home
  numberOfInstances: 3
  # enableMasterLoadBalancer: true
  # enableMasterPoolerLoadBalancer: true
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  enableLogicalBackup: false
  patroni:
    ttl: 30
    retry_timeout: 60
  volume:
    size: 10Gi
    storageClass: longhorn
  preparedDatabases:
    grafana:
      defaultUsers: true
      secretNamespace: monitoring
  postgresql:
    version: "14"
    parameters:
      max_connections: "250"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2500Mi
