---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: home-postgres
spec:
  teamId: home
  numberOfInstances: 2
  enableConnectionPooler: false
  enableReplicaConnectionPooler: false
  enableLogicalBackup: false
  patroni:
    loop_wait: 10
    ttl: 10
    retry_timeout: 5
  volume:
    size: 40Gi
    storageClass: longhorn
  preparedDatabases:
    grafana:
      defaultUsers: true
      secretNamespace: monitoring
  postgresql:
    version: "14"
    parameters:
      max_connections: "250"
  resources:
    requests:
      cpu: 150m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2500Mi
