---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: home-postgres
spec:
  teamId: home
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - home
  numberOfInstances: 1
  enableConnectionPooler: false
  enableReplicaConnectionPooler: false
  enableLogicalBackup: false
  patroni:
    loop_wait: 10
    ttl: 10
    retry_timeout: 5
  volume:
    size: 50Gi
    storageClass: longhorn
  preparedDatabases:
    grafana:
      defaultUsers: true
      secretNamespace: monitoring
  postgresql:
    version: "14"
    parameters:
      max_connections: "250"
  resources:
    requests:
      cpu: 150m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2500Mi
