---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "flux-webhook-${SECRET_DOMAIN/./-}"
spec:
  secretName: "flux-webhook-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "flux-webhook.${SECRET_DOMAIN}"
  dnsNames:
    - "flux-webhook.${SECRET_DOMAIN}"
