---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "flux-${SECRET_DOMAIN/./-}"
spec:
  secretName: "flux-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "flux.${SECRET_DOMAIN}"
  dnsNames:
    - "flux.${SECRET_DOMAIN}"
