---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: flux-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: webhook-receiver
          namespace: flux-system
          port: 80
          scheme: http
      middlewares:
        - name: github-hooks
          namespace: networking
  # tls:
  #   secretName: "flux-${SECRET_DOMAIN/./-}-tls"
