---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "prometheus-${SECRET_DOMAIN/./-}"
  namespace: monitoring
spec:
  secretName: "prometheus-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "prometheus.${SECRET_DOMAIN}"
  dnsNames:
    - "prometheus.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "alertmanager-${SECRET_DOMAIN/./-}"
  namespace: monitoring
spec:
  secretName: "alertmanager-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "alertmanager.${SECRET_DOMAIN}"
  dnsNames:
    - "alertmanager.${SECRET_DOMAIN}"
