---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 6.52.8
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 5m
  values:
