---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/CrunchyData/postgres-operator-examples/
  ref:
    branch: main
  recurseSubmodules: true
