---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: crunchy-data-postgres-operator
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/CrunchyData/postgres-operator-examples/
  ref:
    branch: main
  recurseSubmodules: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zalando-postgres-operator
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://github.com/zalando/postgres-operator/
  ref:
    branch: bump-v1.7.1
  recurseSubmodules: true
