---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
spec:
  interval: 5m
  releaseName: 1password
  chart:
    spec:
      # renovate: registryUrl=https://1password.github.io/connect-helm-charts
      chart: connect
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 1m
  values:
    connect:
      annotations:
        reloader.stakater.com/auto: "true"
      credentials_base64: ${SECRET_1PASSWORD_CREDENTIALS_B64}
      credentialsName: op-credentials
      credentialsKey: op-session
