---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
spec:
  interval: 5m
  releaseName: 1password
  chart:
    spec:
      chart: connect
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 1m
  install:
    # https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource
    # https://fluxcd.io/docs/components/helm/helmreleases/#crds
    crds: Skip
  upgrade:
    crds: Skip
  values:
    connect:
      annotations:
        reloader.stakater.com/auto: "true"
      credentials_base64: ${SECRET_1PASSWORD_CONNECT_CREDENTIALS_B64}
      credentialsName: op-credentials
      credentialsKey: op-session
    operator:
      create: true
      autoRestart: true
      token:
        name: onepassword-token
        key: token
        value: ${SECRET_1PASSWORD_OPERATOR_TOKEN}
