---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pg-hummingbot.${SECRET_DOMAIN}`)
      services:
        - name: postgres-postgresql
          port: 5432
  tls:
    secretName: "pg-hummingbot-${SECRET_DOMAIN/./-}-tls"
    passthrough: false
