---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pg-hummingbot.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name:
          port: 4181
  tls:
    secretName: "auth-${SECRET_DOMAIN/./-}-tls"
    passthrough: false
