---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
spec:
  entryPoints:
    - hg-pg
  routes:
    - match: HostSNI(`*`)
      services:
        - name: hummingbot-postgres
          port: 5432
