# https://access.crunchydata.com/documentation/postgres-operator/5.0.4/references/crd/#postgresclusterspecusersindex
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
spec:
  postgresVersion: 14
  users:
    - name: hummingbot-bots
      databases:
        - hummingbot
    - name: hummingbot-dev
      databases:
        - hummingbot-dev
  instances:
    - name: hummingbot
      replicas: 2
      resources:
        requests:
          cpu: "500m"
          memory: "1024Mi"
        limits:
          cpu: "1000m"
          memory: "8096Mi"
      dataVolumeClaimSpec:
        #volumeName: hummingbot-postgres-data
        accessModes:
          - "ReadWriteOnce"
        storageClassName: longhorn-civo
        resources:
          requests:
            storage: 100Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_locality
                    operator: In
                    values:
                      - "external"
  monitoring:
    pgmonitor:
      exporter: {}
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              #volumeName: hummingbot-postgres-backup
              accessModes:
                - "ReadWriteOnce"
              storageClassName: longhorn-civo
              resources:
                requests:
                  storage: 50Gi
