---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: hummingbot-postgres
spec:
  teamId: hummingbot
  numberOfInstances: 0
  enableConnectionPooler: false
  enableReplicaConnectionPooler: false
  patroni:
    ttl: 30
    retry_timeout: 60
  volume:
    size: 15Gi
    storageClass: longhorn-civo
  users:
    superuser:
      - superuser
      - createdb
  databases:
    hummingbot: hummingbot
  preparedDatabases:
    hummingbot:
      defaultUsers: true
      extensions:
        pg_partman: public
        pgcrypto: public
      schemas:
        data:
          defaultUsers: true
  postgresql:
    version: "14"
    parameters:
      max_connections: "200"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2500m
      memory: 8192Mi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_locality
              operator: In
              values:
                - "external"
