---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: hummingbot-postgres
spec:
  teamId: hummingbot
  numberOfInstances: 2
  volume:
    size: 10Gi
    storageClass: longhorn-civo
  users:
    superuser:
      - superuser
      - createdb
  databases:
    hummingbot-dev: hummingbot-dev
    hummingbot: hummingbot
  preparedDatabases:
    hummingbot-dev:
      defaultUsers: true
      extensions:
        pg_partman: public
        pgcrypto: public
      schemas:
        data:
          defaultRoles: true
          defaultUsers: true
        history:
          defaultRoles: true
          defaultUsers: true
    hummingbot:
      defaultUsers: true
      extensions:
        pg_partman: public
        pgcrypto: public
      schemas:
        data:
          defaultRoles: true
          defaultUsers: true
        history:
          defaultRoles: true
          defaultUsers: true
  postgresql:
    version: "14"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2500m
      memory: 8192Mi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node_locality
              operator: In
              values:
                - "external"
