---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: 3.8.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.6.0
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 200Mi
