---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      # TODO - kube-system/metrics-server tolled back to v0.5.0 until helm chart updates its clusterRole
      # After a release v0.6.0 came out, it introduces a breaking change in which we cannot keep using the same helm chart without fine tuning
      # Release info at https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.0
      tag: v0.5.2
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 200Mi
