---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: networking
spec:
  interval: 5m
  releaseName: metrics-server
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: metrics-server
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server-chart
        namespace: flux-system
      interval: 1m
  values:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 200Mi
