---
fail_fast: false
ci:
  autofix_commit_msg: |
    [pre-commit.ci] Auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip:
    # shellcheck tool cannot be installed on CI
    - shellcheck
  submodules: false

repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - -c
          - ".github/linters/.yamllint.yaml"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck

        args: [--severity=error]

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.0
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.7.1
    hooks:
      - id: gitleaks
