---
creation_rules:
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: ^(data|stringData)$
    pgp: >-
      0x2141D0D63053C652,
      0x03249595A54E0BC8
  # TODO Add support for age as an immediate successor of GNUPG
  #
  # - path_regex: cluster/.*\.ya?ml
  #   encrypted_regex: "^(data|stringData)$"
  #   age: >-
  #     age1e6svnw727k56t7d8lu6hd36reggwaqvkpkv0zjyk5gkkkw0enf9q53g6lf
