---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"

# env:
#   KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  flux: .taskfiles/flux.yaml
  pre-commit: .taskfiles/pre-commit.yaml
