---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.3.31
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/thanos
    query:
      replicaCount: 2
      replicaLabels:
        - replica
    compact:
      retentionResolution1h: 1y
  valuesFrom:
    - kind: Secret
      name: thanos-values
      optional: false
