---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-charts.banzaicloud.com
      chart: thanos
      version: 0.3.31
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/thanos
    query:
      replicaCount: 2
      replicaLabels:
        - replica
      stores:
        - dnssrv+_grpc._tcp.thanos-store-grpc
        - dnssrv+_grpc._tcp.thanos-sidecar-grpc
      storeDNSDiscovery: false
      sidecarDNSDiscovery: false
      ruleDNSDiscovery: false

    compact:
      retentionResolutionRaw: 7d
      # How long to retain samples of resolution 1 (5 minutes) in bucket. 0d - disables this retention
      retentionResolution5m: 30d
      # How long to retain samples of resolution 2 (1 hour) in bucket. 0d - disables this retention
      retentionResolution1h: 90d
  valuesFrom:
    - kind: Secret
      name: thanos-values
      optional: false
