objstore:
  type: S3
  config:
    bucket: "metrics"
    access_key: "{{ .MINIO_ACCESS_KEY }}"
    secret_key: "{{ .MINIO_SECRET_KEY }}"
    endpoint: "minio.minio.svc:9000"
    region: ""
    insecure: true
    signature_version2: false
    put_user_metadata: {}
    http_config:
      idle_conn_timeout: 0s
      response_header_timeout: 0s
      insecure_skip_verify: false
    trace:
      enable: false
    part_size: 0
