---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCQnb/YnRlemxsKg7j15yxI3uaQb0cdojV4suhEv6o1sL9lSbpMYcKALzQZJjkJcHO7e/Wipc7bo76zVgdSW1AhgjpQPF604p/01CkLiQeJi1fALgg9jOkd62hk/rxWnplYHPFhKmtP7N2zBUF2AxYvsPWYkYHz2EZGISRpHAbx2Xf03JJ9Pm5KpXMoMYC8uy1hFyl72f2ZZOn6KzGwgiAIGzLvqErO7wyD1Wh/ZnEYf19+UCCQ/xOxlpJZ9nybZ1QlorracBVSQtIr5QmwrxYblxNsL55WyB1YvQwUMmeSFdVUdk2+DSwZYE4T2h5dmF+H36q5p76mEie+MHkgcZux0S8OArlLFJPE4CjtkKYCv4ut53aKfZpVRpdCDjA2DpIh/e9SKSXA3VJxJ9e4sKWvpO03d5sHH0N9Y8WGNkdBlrGWPYvZUsARRasXNfhGYlrnzTVHbXktLSgG+Lo6PMgkUSYivnkOSW+3CvNsPvP8NvQicPjw2fTX3x7fbmGduZmRs0Yo2fcju+iyegkTOXV1Em7JchFxAqRWDq8Wk0l4q3gu/ts95z8C52ZQlGrmmavsLmajIOsAUQJPMQ7fooZGam1YNZ4ZDiRISwuDXXnJhxdnJkIYeLfxYMWizyNJfFJ3pBCnsquVrK8+h72WKXDrECvhuKdt9Gu05sm2voG1YLzZHWYISA+ehmfql7PCpDvVEZ5Psot2L2rOmq9F3KDg3PumXUHUo9AKPg4bGGWvcm2S8PedmPTObg3UrUewWQ6QbBI3BHQNZvj5R9XlGMm7QdBWClvcvvVfpxYpGB9CFwujz7N6YUQ3JqINTc/zX+2ZcusOwgq8dIa5cgRn75GieXrWscJlfQtdhmNH+xdFhmNKNyn13QogFFgrOEpUIcFQ910NQWsRFSKLRX27yvpBuGLJKjklQg==
