---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  values:
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 0.14.0
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          memory: 174M
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: |-
          http://thanos-query.monitoring.svc.cluster.local:9090

    updater:
      enabled: false

    admissionController:
      enabled: false
