---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbooks
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/evanbuss/openbooks
      # TODO: Replace latest tag for OpenBooks once they had fixed multi-arch support
      #  It seems to be an issue with their latest 4.5.0 release
      #  labels: todo, area/cluster, bug, lifecycle
      tag: latest
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539
    command:
      - ./openbooks
    args:
      - server
      - --dir
      - /books
      - --port
      - &port "8080"
      - --persist
      - --name
    service:
      main:
        ports:
          http:
            port: *port

    persistence:
      books:
        enabled: true
        type: pvc
        mountPath: /books
        accessMode: ReadWriteOnce
        size: 5Gi

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 176M
