---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./certificate.yaml
  - ./ingress-route.yaml
commonLabels:
  app.kubernetes.io/name: openbooks
  app.kubernetes.io/instance: openbooks
