---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha-core
  namespace: home-assistant
spec:
  interval: 5m
  releaseName: home-assistant-core
  chart:
    spec:
      chart: home-assistant
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2020.12.1
    persistence:
      config:
        enabled: true
        storageClass: local-path
        size: 50Gi
    env:
      TZ: Europe/London
    envFrom:
      - secretRef:
          name: home-assistant-env
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      enabled: true
      hosts:
        - host: ha.uk.msrpi.com
          paths:
            - path: /
              pathType: Prefix
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    # additionalVolumes:
    #   - name: sshkeys
    #     secret:
    #       secretName: github-credentials
    #       defaultMode: 0700
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 250m
        memory: 512Mi
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
          hosts:
            - host: hass-vscode.eviljungle.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-vscode.eviljungle.com
        volumeMounts:
          - name: config
            mountPath: /config
