---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha-core
  namespace: home-assistant
spec:
  interval: 5m
  releaseName: home-assistant-core
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: home-assistant
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: traefik
      namespace: kube-system
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2020.12.2
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-pvc
    env:
      TZ: Europe/London
    envFrom:
      - secretRef:
          name: home-assistant-env
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
    # additionalVolumes:
    #   - name: sshkeys
    #     secret:
    #       secretName: github-credentials
    #       defaultMode: 0700
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 250m
        memory: 512Mi
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        volumeMounts:
          - name: config
            mountPath: /config
