---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-certs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
