---
apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.12.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.12.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
spec:
  endpoints:
    - port: metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - kube-system
