---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: miscellaneous
spec:
  interval: 5m
  releaseName: calibre-web-core
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: calibre-web
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: traefik
      namespace: kube-system
    - name: longhorn
      namespace: longhorn-system
  values:
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-pvc
      books:
        enabled: true
        existingClaim: calibre-web-books-pvc
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 250m
        memory: 512Mi
