---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "hass-${SECRET_DOMAIN/./-}"
  namespace: home
spec:
  secretName: "hass-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "hass.${SECRET_DOMAIN}"
  dnsNames:
    - "hass.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "hass-mobile-${SECRET_DOMAIN/./-}"
  namespace: home
spec:
  secretName: "hass-mobile-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "hass-mobile.${SECRET_DOMAIN}"
  dnsNames:
    - "hass-mobile.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "hass-config-${SECRET_DOMAIN/./-}"
  namespace: home
spec:
  secretName: "hass-config-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "hass-config.${SECRET_DOMAIN}"
  dnsNames:
    - "hass-config.${SECRET_DOMAIN}"
