---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chart:
    spec:
      chart: thanos
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      version: 6.0.4
  interval: 5m
  values:
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        enabled: false
    existingObjstoreSecret: thanos-objstore
    image:
      registry: public.ecr.aws
      repository: bitnami/thanos
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    query:
      dnsDiscovery:
        sidecarsNamespace: monitoring
        sidecarsService: prometheus-thanos-discovery
      enabled: true
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        enabled: true
        hostname: thanos.${SECRET_DOMAIN}
        ingressClassName: traefik
        tls: true
      replicaLabels:
        - replica
    queryFrontend:
      enabled: false
    ruler:
      enabled: false
    storegateway:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
