---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.31.8
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  # dependsOn:
  #   - name: minio
  #     namespace: tools
  values:
    configuration:
      extraEnvVars:
        TZ: "Europe/London"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: k8s-home-velero
        default: true
        config:
          region: eu-west-2
          # s3ForcePathStyle: true
          # s3Url: "http://minio.tools.svc.cluster.local:9000"
          #s3Url: https://s3.${SECRET_DOMAIN}
      resticTimeout: 4h
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      existingSecret: velero-s3-creds
    schedules:
      daily-backup:
        # At 6:00am in the morning every day
        schedule: "0 6 * * *"
        template:
          ttl: "168h"
      weekly-backup:
        # At the end of the week on a Sunday morning, at 6:00am
        schedule: "0 6 * * 0"
        template:
          ttl: "672h"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    backupsEnabled: true
    snapshotsEnabled: false
    upgradeCRDs: false
    cleanUpCRDs: false
    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.25.2
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
