---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 4.0.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    annotations:
      secret.reloader.stakater.com/reload: velero-s3-creds
    configuration:
      extraEnvVars:
        TZ: "Europe/London"
      backupStorageLocation:
        - name: default
          bucket: k8s-home-velero
          provider: aws
          default: true
          config:
            region: eu-west-2
      resticTimeout: 4h
    credentials:
      existingSecret: velero-s3-creds
    schedules:
      daily-backup:
        # At 6:00am in the morning every day
        schedule: "0 6 * * *"
        template:
          ttl: "168h"
      weekly-backup:
        # At the end of the week on a Sunday morning, at 6:00am
        schedule: "0 3 * * 0"
        template:
          ttl: "338h"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        spec:
          - alert: VeleroDailyBackupPartialFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partially failed backups.
            expr: |-
              velero_backup_partial_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
          - alert: VeleroDailyBackupFailures
            annotations:
              message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
            expr: |-
              velero_backup_failure_total{schedule="velero-daily-backup"} / velero_backup_attempt_total{schedule="velero-daily-backup"} > 1
            for: 15m
            labels:
              severity: warning
    backupsEnabled: true
    snapshotsEnabled: false
    upgradeCRDs: false
    cleanUpCRDs: falsex
    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.27.2
    deployNodeAgent: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
