# yamllint disable
# cloud :|
#     [default]
#     aws_access_key_id=<ACCESSS_KEY>
#     aws_secret_access_key=<SECRET_KEY>
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: velero-s3-creds
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:O1aBfh+NIWl585fXtiapMHKhY0x9+KnwqjJkdYexcooHw0/XLP6qJOqkGXJhh8g2z1EsSEkb2+LoWfcb8c8L5B0cnKZjkcHmFC70MUWP3+BjRvB+/eaDjT1KSR1014thY19NJiWTI8cb65yFGV2pNw==,iv:zvXuXrpRsRx6XmcZ9QPi3DbXJh0ihnO9stptB7fCXQM=,tag:vhh1rzIhLUO9FSW7K4c4Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-08T20:14:02Z"
    mac: ENC[AES256_GCM,data:hRs4FHeAPcFV2YXfhPoJfHlUPQMs98A4Xg8VWDbXkBeKCzqsK8QNay2G6EjDX2pMFI5XOHw0SehlLzMs+mLFMYxX0u1qjeWuB1U5JYVyIxt/0naj8eC08P2VQihYiHfOVpdZcom4Hl/kxvGe469FeYgvRT27i+hrmCQ23oiW5Co=,iv:evxGZuMDt++vb3GaN9d7lyaLwQG0Er43xqxRE84wulU=,tag:o1fuEhn2qoTQvgAMitrQAQ==,type:str]
    pgp:
        - created_at: "2021-10-01T00:01:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3t//ZLkhd3HAQ//bfBeoEZAqZY7TZeIRNML2f2MTRf9dAr/cbgLjvmRdMJ8
            /bPb5Uguug83kzIRLHzwk1FN/F6PbfUkVc84QJyrrjTFlSfWjqm3aVeD2ThKAQP7
            cmnXltkXu3S2RfJjPLVJAEUC/zrTx05+7xKRmJZujGYYHlxs5ohYG7lAhWNFbPVh
            u/+4dwBxDis5Iu5gMTZV2cxEziUkd0fVXPmheMgGXLWEVihO0pqjHDtiJM9L4CRH
            UBsWGT4uxQl98/AhMwA4lcfRJOckKp9RO1URNxAC339ToVsolyQ4LaUOv/QFdsB4
            ct7v+z5NGTqmJCT8ssIuFUAgP4GdBWPRuvEmSosH4Eu/JPIBKjxpkbwqUmX3o0n+
            luXbVKhOc9nbPgkM5akdOYBlAzYwfzIpcC6Wv7Fg2ZtTPbSwQr61u2EvaIBoS3Kt
            NueSkTNjtvDiPz2zMHnI0KGlclW3rff8zZ+/9I5VmDebNMZeYptLZgzA4y1JvDaf
            bGodKFJdcl2ZT+jc6Hm0vVuUiu5iZTtn30toP9cuiqEBDbmVa893/KceuP+8n+RU
            u08/KOpY8fyTheNOejKg+p1TOkugJIbdCQEDD86pMm78WF61Ua3yMZVecC54IQaV
            jrILXxigORA4UCENcvp/7OStaLJfy0/rdIC1B1PMOPaCmnM3cqjD8QBdlBwqCarS
            XgGkUG34/eibHKQCuAPoF/wV1HNBSoY9kGed2ETXcZEt9oIoVzfp3AsinRU3WYVT
            FC1EJdwd93HFCs+LOqtpYUgem1dX1DPDC45VJzAIwW+m/wdMcBIAuqvB+TGUV9E=
            =SeF5
            -----END PGP MESSAGE-----
          fp: "0x2141D0D63053C652"
        - created_at: "2021-10-01T00:01:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwMklZWlTgvIARAAhjADBbbbCX+h67boCVsEBtdnbQOgEiSKzglP+WrwJDtV
            9fhKqyjgX0VQpAI+IRNu4vllR7tIuGyayDLPa80QyndYVYvvHRSiBd8hDY+gT+Cg
            pE+edsygSScvrqMnIiYKVx7IB5VQxCtPOWOaoLa+RaNku5IcXEfc80vyE78tHpg3
            XzkALAHJwKBlR3x3UnXF9ILKMgWNJq4s1wyRhi4vPFPTbaB+PrrMsCE0eE74C9pE
            XUnDlZHN3yN3yQ0qp2C/l0VUZF5PKen461GiLcAbqGCW9UmUP/F5wQB8nRjch9nq
            bhT9S3hfduqX9Y40/hstv9hFhCV1+r9YPNkwRTtmRXgxYNvuraxQmHQSPt5Xp6TB
            DMcfWzmqDZYw1FDPVwX70UTtzqrUkZqcu0ipzhIuwc0OIYfDAM1Clsf9NrxO+APy
            dZZyssCulAo/QsURrFbMTtBiIvU0QH/E6bQSOzjRWibMZ2K4yFDehwvBDPUjCjBk
            DRXaS3mTpS/ocSgg4MFJ32wDHdNEIHCXmdNYQ5yEyGDjO22TewkoUu/krhf3cBsQ
            darWz9WeiUmv9N8l7lIS95ar61AHdpbmpUTPpRWmSgjFjCP/pBaoyaMCW6SSnidl
            vEi9z7bURBfCz2058n4kZgJLY0lZX6IkNPat/WBAFeGUyuz0PvclrkiNDj64iRTS
            XgHWmjOGMZMatImyC3yI6EjVOvFyiDSqVBLK4jfsvIcsmPcLicO2YSEQWxwEGUbT
            wMBeBGfKFD3vlKzACdkZve9WOWd9geBzODPiWu6xciOaHORPLoRCO/m6K2sRsOY=
            =+f86
            -----END PGP MESSAGE-----
          fp: "0x03249595A54E0BC8"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
