---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "goldilocks-${SECRET_DOMAIN/./-}"
spec:
  secretName: "goldilocks-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "goldilocks.${SECRET_DOMAIN}"
  dnsNames:
    - "goldilocks.${SECRET_DOMAIN}"
