---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  dependsOn:
    - name: vpa
      namespace: monitoring
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 145M
        limits:
          cpu: 1
          memory: 174M
    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 1
          memory: 64M
