---
apiVersion: ingressroutes.traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`influxdb.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: influxdb-influxdb2
          namespace: monitoring
          port: 80
          scheme: http
  tls:
    secretName: "influxdb-${SECRET_DOMAIN/./-}-tls"
