---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 1m
  releaseName: traefik
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 9.18.3
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    deployment:
      initContainers:
        - name: volume-permissions
          image: busybox:1.31.1
          command: ["sh", "-c", "chmod -Rv 600 /data/*"]
          volumeMounts:
            - name: data
              mountPath: /data
      dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      general:
        level: INFO
      access:
        enabled: true
        fields:
          headers:
            names:
              X-Forwarded-User: keep
    additionalArguments:
      - --providers.file.filename=/data/traefik-config.yaml
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      # - --entrypoints.websecure.http.middlewares=kube-system-traefik-forward-auth
      - --certificatesresolvers.cloudflare.acme.email=marcos.soutullo91@gmail.com
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.cloudflare.acme.storage=/etc/traefik/certs/acme.json
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.delayBeforeCheck=0
      - --metrics.prometheus=true
      - --entrypoints.metrics.address=:9090/tcp
      - --metrics.prometheus.entryPoint=metrics
    envFrom:
      - secretRef:
          name: traefik-env
    volumes:
      - mountPath: /data
        name: traefik-config
        type: configMap
    service:
      externalIPs:
        - 10.10.10.54
        - 10.10.10.60
        - 10.10.10.62
        - 10.10.10.64
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "1000m"
        memory: "350Mi"
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      traefik:
        expose: false
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          certResolver: cloudflare
          domains:
            - name: "*.uk.msrpi.com"
    persistence:
      enabled: true
      existingClaim: traefik-certs-pvc
      path: /etc/traefik/certs
    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
          - TLS_AES_256_GCM_SHA384 # TLS 1.3
          - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
        curvePreferences:
          - CurveP521
          - CurveP384
