---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    global:
      nameOverride: changedetection-io

    image:
      repository: dgtlmoon/changedetection.io
      tag: "0.45.7"

    env:
      BASE_URL: "https://change-detection.${SECRET_DOMAIN}"
      WEBDRIVER_URL: http://localhost:4444/wd/hub
      TZ: "Europe/London"

    service:
      main:
        ports:
          http:
            port: 5000

    persistence:
      config:
        enabled: true
        existingClaim: changedetection-io-config-v1
        mountPath: /datastore
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm

    podAnnotations:
      backup.velero.io/backup-volumes: config
      pre.hook.backup.velero.io/container: fsfreeze
      pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/datastore"]'
      post.hook.backup.velero.io/container: fsfreeze
      post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/datastore"]'

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi

    additionalContainers:
      chrome-webdriver:
        name: chrome-webdriver
        image: selenium/standalone-chrome-debug:3.141.59
        imagePullPolicy: IfNotPresent
        ports:
          - name: web
            containerPort: 4444
        volumeMounts:
          - name: cache
            mountPath: /dev/shm
      fsfreeze:
        name: fsfreeze
        image: ghcr.io/k8s-at-home/fsfreeze:v2.37-r0
        volumeMounts:
          - name: config
            mountPath: /datastore
        securityContext:
          privileged: true
