---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: tools
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      annotations:
        backup.velero.io/backup-volumes: config
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/datastore"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/datastore"]'
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: dgtlmoon/changedetection.io
              tag: "0.48.03"
              pullPolicy: IfNotPresent
            env:
              BASE_URL: "https://change-detection.${SECRET_DOMAIN}"
              WEBDRIVER_URL: http://localhost:4444/wd/hub
              TZ: "Europe/London"
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 750Mi
          chrome-webdriver:
            image:
              repository: selenium/standalone-chrome-debug
              tag: "3.141.59"
              pullPolicy: IfNotPresent
          fsfreeze:
            image:
              repository: ghcr.io/k8s-at-home/fsfreeze
              tag: v2.37-r0
              pullPolicy: IfNotPresent
            securityContext:
              privileged: true
    global:
      nameOverride: changedetection-io

    service:
      main:
        controller: main
        ports:
          http:
            port: 5000

    persistence:
      config:
        type: persistentVolumeClaim
        enabled: true
        existingClaim: changedetection-io-config-v1
        advancedMounts:
          main:
            main:
              - path: /datastore
            fsfreeze:
              - path: /datastore
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
