---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: speedtest-exporter
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.3
    metrics:
      enabled: true
      serviceMonitor:
        interval: 15m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
        downloadLimit: 150
        uploadLimit: 20
        pingLimit: 30
        jitterLimit: 30
