---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    loki:
      # image:
      #   repository: grafana/loki
      #   tag: 1.5.0
      replicas: 2
      ingress:
        enabled: false
      persistence:
        enabled: false
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        distributor:
          ring:
            kvstore:
              store: memberlist
        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
        memberlist:
          abort_if_cluster_join_fails: false
          # Expose this port on all distributor, ingester
          # and querier replicas.
          bind_port: 7946
          # You can use a headless k8s service for all distributor,
          # ingester and querier components.
          # max_join_backoff: 1m
          # max_join_retries: 10
          # min_join_backoff: 1s
          join_members:
            - loki-headless:7946
        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: index_
                period: 24h
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/index
            cache_location: /data/loki/index_cache
            resync_interval: 5s
            shared_store: s3
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
      extraPorts:
        - port: 7956
          protocol: TCP
          name: loki-gossip-ring
          targetPort: 7946
      serviceMonitor:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http-metrics"
    promtail:
      # image:
      #   repository: grafana/promtail
      #   tag: 1.5.0
      serviceMonitor:
        enabled: true
      tolerations:
        - key: "arm"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      extraScrapeConfigs:
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            label_structured_data: yes
            labels:
              job: "syslog"
          relabel_configs:
            - source_labels: ["__syslog_message_hostname"]
              target_label: "hostname"
            - source_labels: ["__syslog_message_app_name"]
              target_label: "app_name"
        - job_name: journal
          journal:
            json: true
            path: /var/log/journal
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels: ["__journal__systemd_unit"]
              target_label: "systemd_unit"
            - source_labels: ["__journal__hostname"]
              target_label: "hostname"
            - source_labels: ["__journal_syslog_identifier"]
              target_label: "syslog_identifier"
      syslogService:
        enabled: true
        type: LoadBalancer
        port: 1514

      # Mount journal directory into promtail pods
      extraVolumes:
        - name: journal
          hostPath:
            path: /var/log/journal
      extraVolumeMounts:
        - name: journal
          mountPath: /var/log/journal
          readOnly: true

  valuesFrom:
    - kind: Secret
      name: "loki-stack-values"
      optional: false
