---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaeger-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://jaegertracing.github.io/helm-charts
  timeout: 3m
