---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metrics-server-chart
  namespace: flux-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/metrics-server/
  timeout: 3m
