---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/vmware-tanzu/helm-charts.git
  ref:
    # TODO: Automate velero CRD auto-upgrade via Renovate bot
    # renovate: datasource=helm depName=vmware-tanzu/helm-charts
    tag: velero-3.0.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/charts/velero/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: velero
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: backups.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: backupstoragelocations.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: deletebackuprequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: downloadrequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podvolumebackups.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podvolumerestores.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: resticrepositories.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: restores.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: schedules.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: serverstatusrequests.velero.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: volumesnapshotlocations.velero.io
