---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "change-detection-${SECRET_DOMAIN/./-}"
  namespace: tools
spec:
  secretName: "change-detection-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "change-detection.${SECRET_DOMAIN}"
  dnsNames:
    - "change-detection.${SECRET_DOMAIN}"
