---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io-config-v1
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
