---
alertmanager:
  fullnameOverride: alertmanager
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: false
    ingressClassName: traefik
    annotations:
      app.kubernetes.io/managed-by: "Helm"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "kube-system-traefik-forward-auth@kubernetescrd"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "cloudflare"
      traefik.ingress.kubernetes.io/router.tls.domains.0.main: "alertmanager.uk.msrpi.com"
    paths:
      - "/"
    hosts:
      - "alertmanager.uk.msrpi.com"
  retention: 120h
