---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: kube-state-metrics
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    image:
      registry: quay.io
      repository: coreos/kube-state-metrics
      tag: v2.0.0-beta
