---
prometheus:
  fullnameOverride: prometheus
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "kube-system-traefik-forward-auth@kubernetescrd"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: "cloudflare"
      traefik.ingress.kubernetes.io/router.tls.domains.0.main: "prometheus.uk.msrpi.com"
    paths:
      - /
    hosts:
      - prometheus.uk.msrpi.com
  prometheusSpec:
    # image:
    #   repository: quay.io/prometheus/prometheus
    #   tag: v2.20.0
    replicas: 1
    replicaExternalLabelName: "replica"
    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    retention: 6h
    enableAdminAPI: true
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          resources:
            requests:
              storage: 10Gi
    thanos:
      image: raspbernetes/thanos:v0.17.2
      version: v0.17.2
      objectStorageConfig:
        name: thanos
        key: object-store.yaml
