---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  suspend: false
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 13.1.1
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 5m
  timeout: 20m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    prometheusOperator:
      enabled: true
      manageCrds: true
      createCustomResource: true

    nodeExporter:
      fullnameOverride: node-exporter
      enabled: true
      serviceMonitor:
        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node

    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance

    kubeControllerManager:
      enabled: true

    kubeScheduler:
      enabled: true

    kubeProxy:
      enabled: true

    kubeStateMetrics:
      enabled: false

    kubeEtcd:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: "grafana-values"
      optional: false
    - kind: Secret
      name: "prometheus-values"
      optional: false
    - kind: Secret
      name: "alertmanager-values"
      optional: false
