---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: Flux
  channel: flux
  secretRef:
    name: discord-webhook-url
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Alert
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
  exclusionList:
    - "error.*lookup github\\.com"
    - "waiting.*socket"
  suspend: false
