# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:B/8kNOlKu6iqE2ra59mH9zKHRqk2z/HEgddrvvY9cI4x6UXpvzPv4Z7AF+1DrjQoN8zL/HC8559V1LRxr4R4v8Ww7960gjGVo2wfOlU6peE5hxVrybKAh1jSMQ2nT88BwxlQNmI9NhYwkc+o21rC04/AazM3PPeS5tHI,iv:b4vSZbMbT7Ake8Ld45U3qxqfgQZi4MSykNqUN6cL43k=,tag:EPNTxMVGcWmVnYS39LGElg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-25T18:37:57Z"
    mac: ENC[AES256_GCM,data:syqusNcGdCG4XVqgnXrZNKvwRZ9YghnPqpDcF42PDSoDD7f27icPkr+OQEl/zszzvkmOw96qx9v85Wsxnguuz7tzT/r5rP0TzLhZaeF+sIoqIL1FQZkeN9KAZTsrjNZRYEv8bzzMBljthkXMSFmFPJGK4EzLgc5pCnEo0euFzKg=,iv:mATQ5CMInU+/jHx7LYWYX5x+1a7AE8gQnlbmZIouDmA=,tag:KmVK/8rq+yT4plLT9pUHWQ==,type:str]
    pgp:
        - created_at: "2021-07-25T18:37:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3t//ZLkhd3HAQ/+Mtsr9KHMLbLGqIF+KqkHEKFMEhRoG2XwWPzoghCUbvXh
            KkmgfKolbDOna5yn10l+MTC1BiSRBmPJylXCF3H5aW10zeR6OoiEMiMCMFnRBe2K
            1+ImJ3wL+aWSBFSXKPHxaUxbtk5d0irARWpotxh+tcC+C+4UF5nCZbri2P05b6A3
            OmWCv5j3AMArfNDft/OxgOyswRYhG6JUrNFzC6GXb/hSWmoN4bpJH6SYbrU3ToOI
            dFAKSSW7U7IlHZ7lAd1Os9tcWqQ+A9H/mqWzZnEFEnRaNoCkhvd+2sZz5E0zHyAr
            buM7o1zxKV6eLwdsQ8fq5knIkPAOUEbQUodduXMfdhzDs9D1C7mry6KdyTcJfIJZ
            NRe4D1Ul5+uSIr/KtBLMpyKh4KB03pVm8EcCPq+4t3VYbKfeEvuDYaJ3Fj8vPdwj
            w08WZa/TThj11wOlDgRLfHuBJ5El5TApO0aklQ6d9fIiBjwlMOvyjPBfzvNRzXOm
            PCmIYTa0y6t5KBXt/8tR1XN7waAyE27VdALzam4OZbaAeTrC6C1+8Fy5rkdC3eBf
            iLlV9ocD/PJm3Z+xElQqX2EU04okRykNXtI4Z/DoOg+Rh3pwNO7rBqeYYgcHBfn9
            on4BXgn8gAEFlMVlVx/tv2SWOOJR3DF1IbT9WkZgdjqRvha5Jo8tEVkJWZxpZufS
            XgEhdWQr6u4wDZAHIfnJ31wdm+cuqKraRV7VkYaPI66uQix9Fh27iijfoS6SJFjg
            Pxnjvr35HZQLwUAcBddgZfiLcck/NdCdeR5lsL/64osniE9iyMRkhX6EuaiohSU=
            =E+tK
            -----END PGP MESSAGE-----
          fp: "0x2141D0D63053C652"
        - created_at: "2021-07-25T18:37:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwMklZWlTgvIARAAntZe/TpEYSX23I2v0ofIaUV3wNx0FojKU/wsBi6Q0OJX
            tHIzcuEZPCro/rnyM6j6cHgIegfuc+znJr1rSk5tc4A6APX0SrFcC0p5cOIgyBIb
            xmjwg6KyeCicqyTBLEUY5OHYMbr259+SML6tl642XdylHgIxnXnrAn/ifDi9qZ2j
            0nJzp+PuBP+QeIzuzOZ1c/n4q11qkWLx+B2ntTm6fTzL1M2CFWPAD7svMz7R3/GK
            +ahG/8bHyiy/yq9yhX78aizp9JTVLqB7yKIauqamblTPBQjkynE0oh/hRdzC7qLE
            SpO+Tj2Hxtxjn9/65PeO+s9HBFB0w90KsReqWRAV4vmRzNpY8QB+evEnPTQtKDw8
            N9pNpDcGZHZEUVkqkHRbgEHQ7Ka/noquwUNHXgB1Njwt7ebdyF9QkeplOcxCHhvY
            /z/gfbUG96IdRWellcj3nrX4dSOsQ+pw6MocZe07GLnH/DkUGjJwK91THN36QIqi
            Bk/+VlVr9H6rE6GUwcsFw6oHnttqx0UD2dhqQeOPXGZUU8pBgK8e2riEk9AmRh7A
            mzkJfbk/HrlmJEnr7lbMrDi29dCriAgqn4NsOqfQIHWZJeFUulv47BOjL9zR07tC
            zbQtnYt/7Z0LzLb2NjsNXEMOWrMgl1vzEY4+7LYefRyheYewYU1eWZGSU0bxkRbS
            XgH20lYugwOXdDlYI2o4QNGqgVVsQAK8/Vq2x3jc7C4sXrJO7mF+vjmz76qlCED9
            clTM/YhGXfDQ84azexJIblcLRo4xioXKa4At+pEf4TX7nUHL3jMORugIXmRyays=
            =YmE5
            -----END PGP MESSAGE-----
          fp: "0x03249595A54E0BC8"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
