# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-key
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:Rv6ZgoL8iMVAq9TTpASfzbeY9qOp6mE2mK9auNO4p5//XCq/Op7J5mAvRFq8OFphYnJVxFtSs09TAVyyVdzkcjOL7NUXa6GpH0m5z8u7uHIGCj757iNIfrA8lplN+rKxrDym7TdM0TnbXwej9XmWp87fOZ8W6wK72wgz3KZBDKHDO1VTlk1KA2Iv5nQXrCDuBN9mllH0nPXCjKZCSvXTqcgKBYIj/1PTOMsoQO1vU/xCMOvI1G26GYwfp81CGpmJV3+6RIFywJP5R/DX5Ad1nGsfWFWv5lxJkIdXrFPxdA+t1mJB6O7wVXhCPUyNeygqiHDwNoCsZywP8PUfOqqJsGbgfpX9FiYQoDoZ2ivKeEWAfW4IVKdnnVA83AekPMRf0EDXYeJhJoJXCKXdH6yoViy3O3o35X2MsKC/IIXs7BYY3sa7yE14Rv8G4rrEZPJrn33ENSkm+9ujVJ06tMm5OI/9MiOpa5reeSbd9keS3RDuo0XV33V9EKw/bParaoQcXatlTsJbjilFuSpSKLTVIJGWVHSVGfcnNADBC7Q0xllfFmR4W7lpkljVKaelmrvl7TGNoF9bYQvpLgBQ/N8ot8JOWeBjJxko32P4ebnGk6+eWxW7k08c97OUrAnh0vsghLsw/lyf1PKXrgHSHJiXlUFSGz67dF6ItSmqIqxA2+9nomKrXe4YWV9RgpY14lX73viDndIdItyG0vKkSmGa4ZZj77tuauB/zP9bE+KLPniBV1IknEgw3encD7Rv4NIoHwnBcEb2/HZzdImUjJS4SM/uXZcBqc1TmUYw6E4W+M2buJzoz+Rj7csL9aqnBYTubF405DdCLP+3d2x9HNe+4P/qRvKEBvvEQBT6HPU9r2NvSk6DLzgPHqOD5udhP+vFNFOuyxft+mCTguzzR498fRug2fEVv2I+rHg2atrlgRdOnrCwOg/4SzjD6K8/0qeLuK6MMpzu+h/HgzrTwvZRCg==,iv:eve4+F4ytCjscbjmDQrfKo9gMau0uYJ7H0lFhZQezzY=,tag:qMJG4GOAnrGsS5+s4upn8A==,type:str]
  #ENC[AES256_GCM,data:r9bZ3BT5O65hU5u9qXkwwxvLnY4yGDGlv8/y/e+eK3k8spsLQKmnhF12e0s+TqDmfsl2+9DxkiVgDdTyeNMFb4vxTJtqov0sA6TocgBdL3AKkslZaB27iv5P4x8CSxFXMQ8/,iv:5nWsMTm85hKbL+NmaGxC4yraXsY+K/LvGLkysqObq8Y=,tag:F0r9HeStHfWHtWSyn6h5fQ==,type:comment]
  known_hosts: ENC[AES256_GCM,data:0r2wUdTKxRhCYRM3XxjvIzRoiWXcrIZRZFblQ1YPV0UsiX7pNMO6gs1B7ehi0vMcU5oQzm2ZJbu3OTq3fXRxJvWFnLDfJSPC8MsI+xF2yN8du7jF5/JnVqoEa0hgiHBwMndDR5kfrOoZ9pzYTXlHLkbFOAvMfAHyCutbZ46bQ3BbB7n0/HIFHo8b4Zs6j1jpc6ZeZegk3w1emeFemOAIWRKt5bzbNLljP1Vm2e9rYXlXTv31GGn5k8ikaFYZykCPBlY5+tXAiaCoA04kXsLwyie5t5E41Jw6Gmxbn1MeRTqtcbyiJaycOSuHU3poKiRemFBGPuGKlPnzJ9iX6WKN+jqxu/I9slQ+mf5C//60zVLW5wo//qIp5vpmgls70gwEm1cFxyZFUjW6np7O7c24zf4jk4p8yEpQ3ttIoxGg1qGi/W7NZuIIf1m2UuHFxxHl/Ssj8Q/CZg4wnAqVE6T5OwVyjFIKHjgvc8BEeuiRuTHo5d10+8e8DUeswo2AMezzaNq60u2QQeoXr4spt1HnZ1hwzVwvaiqredq2Ba2blkNCzxUd0yiOXvQ7KGvRUsgO/aT/wgb4lyHQxEa0r/9UiEqa5XAL7APwxPo6fzgYx8kVwqc4kNJd7YAzxeZaTeTKu2bHft1i0BFaVxThvJhZ4RG0PE6y3KMfFZMXI4oX27bxHWUmzdW//dmJXzIOYbGunxOAEeFaZbIWUjxFEm4abwhO30IUQMNKkP3E0WNk2vY31TrKFBeSBYy9bOpWN5Fk+K+wqeD2lVjgDQyrU06CPM9rOiBWdqtw6glPZcozG6XViBl8yrRwKyWvrN5jBCJ/5N6vYvnee/QsIeDx8A7S0mk6j31tNdjocN38JzMPYtuJccRC49VjPisPm74ZjEG+xmp2m7+jJZCOtpCcweoANaZmTfCk8vatBjwCzkKMYq/wrFmZiOPWQVrciDHHnMnymqjTBdA26fOt+Ocg9CE6PXxPR/oJc7xDfIDRx0p3KP8FCIFZD6YZIhSkoWRHn02X+bc3+UICBtdrzHI+H4PmuY6unuZtHpyOs3XgMsT71Ovkju2gUqW7xFt67awjmWUvPwKQ/9S9ZiYvznGZ,iv:7GfKyr9r+DFvESlw37Xm6ecMgzln0LDjisNDoIaKrFM=,tag:RFVOoUe9JPUccukux3+BOg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-12-06T23:36:18Z"
  mac: ENC[AES256_GCM,data:KPyPkN7dpw+rPdt18Zcac8kRYSFlGIEHnSSJFPVd2UbKmLnTLCOwybxtF95+KneLu5Dg+UzmYTtR4bZ1jVqerDJ0LyGNXv29oyt3x511AEVOYBTxseQK3Emt22lFgHpCziZ70QoNWaSs4pkX+PQkpY+fscEgjjvGX2GbGOqaUb4=,iv:Q+xX1NgrLY8CEMM1rB1WPBKvj0cYBbc+M0ZRdGBQxks=,tag:WBUzZo2gz7yJFy8Za5D43w==,type:str]
  pgp:
    - created_at: "2022-09-27T20:32:12Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA3t//ZLkhd3HAQ//Q8zsPRwxcYW5Tf9lQuMxn9SNWbgMC9NBixBXvK5BRdus
        SmrAclunsJxXWOeyw99QZPVPfix56SLJyuD+XO1R8hxCShnQeAjodVwvJOG1rBf0
        DTGHN0KZZBTDizF7UitE7k1sZZGf4rHo8is6eKZuorYXdyqRj1X4OWQfwupIi0Oh
        fBomIQdSE4f4X0N6rprFH8ltGbJKClxqzGxkzKg84TYOpoBzMjd/xFn6UHYuUkUE
        2NIQ1X8LFEm7SeLvMOZjdM2R/PghgKoa4Oa1O+ADtJGZO2cE8MypwYsqXPyZzIvn
        vEfhrskHzS5gvPuKisrLOski5QzE/M3n+mxD7K5xFVNXKAv/0H8AVqPfEH4Wtbcu
        icoeemK1sNuQ7J9ir4jEEYRzGTEdDVvMCLgF9aQzGVUXBanToxCNHl3EFLazUKP/
        MhFgpnV5jrT/KWNZho2ltkSfUP6P3i07Q/F0XxlgIoxYoAuX19zVVytN5vcdtW13
        6tavqq2W135KLLj+vhE1rmldf9/BeSoVXqEVQJxoPbiwjzI6xSTvj8Jw91aALBbS
        mMO6lKMN1bswsGDajCCHBJU+B10cGTsMeKZGw0+4kI+MxDyRpmOOCK77aCVDIhZy
        zxeloYF2DZ7nysBWKkv10qnOxDwaM0BizrcpODKBxzXcTb2UQjEyNzBbBvJtJY/S
        XAFqHR9CzmVkf/FPuMR3u20u9frbZAPxEU241oNEvVqhi26xKXh5LIatp6x0onFo
        a2gLiqP69PPvVJMQ44tVUjbdFUV3Q5ilg4YA4zNcVh2OrWC40lXI4IoTCwcr
        =MDb6
        -----END PGP MESSAGE-----
      fp: "0x2141D0D63053C652"
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
