---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 1m
  releaseName: sealed-secrets
  chart:
    spec:
      # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets/
      chart: sealed-secrets
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
    namespace: kube-system
    # serviceMonitor:
    #   # Enables ServiceMonitor creation for the Prometheus Operator
    #   create: false
    #   # How frequently Prometheus should scrape the ServiceMonitor
    #   interval:
    #   # Extra labels to apply to the sealed-secrets ServiceMonitor
    #   labels:
    #   # The namespace where the ServiceMonitor is deployed, defaults to the installation namespace
    #   namespace:
    #   # The timeout after which the scrape is ended
    #   scrapeTimeout:
    # dashboards:
    #   # If enabled, sealed-secrets will create a configmap with a dashboard in json that's going to be picked up by grafana
    #   # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
    #   create: false
    #   # Extra labels to apply to the dashboard configmaps
    #   labels:
    #   # The namespace where the dashboards are deployed, defaults to the installation namespace
    #   namespace:
