---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=helm registryUrl=https://charts.jetstack.io depName=cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/1.12.4/cert-manager.crds.yaml
