---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://charts.jetstack.io datasource=helm depName=cert-manager
  - https://github.com/cert-manager/cert-manager/releases/download/1.11.1/cert-manager.crds.yaml
