---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    persistence:
      defaultClassReplicaCount: 2
    csi:
      kubeletRootDir: /var/lib/kubelet
