---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "karma-${SECRET_DOMAIN/./-}"
  namespace: monitoring
spec:
  secretName: "karma-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "karma.${SECRET_DOMAIN}"
  dnsNames:
    - "karma.${SECRET_DOMAIN}"
