---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha-core
  namespace: home-assistant
spec:
  interval: 5m
  releaseName: home-assistant-core
  chart:
    spec:
      chart: home-assistant
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
