apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/discord-notifications.yaml
  - home-assistant/home-assistant-env.yaml
  - kube-system/traefik-dashboard-bauth.yaml
  - kube-system/traefik-env.yaml
  - kube-system/traefik-forward-auth-env.yaml
  - monitoring/kube-prometheus-stack-values.yaml
  - monitoring/loki-stack-values.yaml
  - monitoring/thanos-values.yaml
