---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - cert-manager
  - system-upgrade
  - kube-system
  - networking
  - longhorn-system
  - monitoring
  - tools
  - velero
