---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "auth-${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "auth-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "auth.${SECRET_DOMAIN}"
  dnsNames:
    - "auth.${SECRET_DOMAIN}"
