---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 1m
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: 2-arm64
    logging:
      level: warn
    format: pretty
    logoutRedirect: ""
    middleware:
      enabled: true
      name: traefik-forward-auth
    env:
      - PROVIDERS_GOOGLE_CLIENT_ID: ${SECRET_PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET: ${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}
      - WHITELIST: ${SECRET_TRAEFIK_AUTH_WHITELIST}
      - COOKIE_DOMAIN: ${SECRET_DOMAIN}
      - AUTH_HOST: "auth.${SECRET_DOMAIN}"
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    providers:
      google:
        enabled: true
