---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 1m
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: 2-arm64
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
          topologyKey: kubernetes.io/hostname
    logging:
      level: warn
    format: pretty
    logoutRedirect: ""
    middleware:
      enabled: true
      name: traefik-forward-auth
    env:
    - name: PROVIDERS_GOOGLE_CLIENT_ID
      value: ${SECRET_PROVIDERS_GOOGLE_CLIENT_ID}
    - name: PROVIDERS_GOOGLE_CLIENT_SECRET
      value: ${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}
    - name: WHITELIST
      value: ${SECRET_TRAEFIK_AUTH_WHITELIST}
    - name: COOKIE_DOMAIN
      value: ${SECRET_DOMAIN}
    - name: AUTH_HOST
      value: "auth.${SECRET_DOMAIN}"
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    providers:
      google:
        enabled: true
