---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik-forward-auth
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: traefik-internal
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 1
        surge: 1
    image:
      repository: ghcr.io/kitos9112/traefik-forward-auth
      tag: v2.6.6
      pullPolicy: IfNotPresent
    middleware:
      enabled: true
      nameOverride: traefik-forward-auth
    env:
      LOG_LEVEL: trace
      LOG_FORMAT: pretty
      LOGOUT_REDIRECT: "https://www.google.co.uk"
      WHITELIST: ${SECRET_TRAEFIK_AUTH_WHITELIST}
      LIFETIME: "28000"
      URL_PATH: "/_oauth"
      AUTH_HOST: "auth.${SECRET_DOMAIN}"
      COOKIE_DOMAIN: "${SECRET_DOMAIN}"
      PROVIDERS_GOOGLE_CLIENT_ID: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID}"
      PROVIDERS_GOOGLE_CLIENT_SECRET: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}"
    resources:
      requests:
        cpu: "25m"
        memory: "25Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    nodeSelector:
      node_locality: internal
