---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: kitos9112/traefik-forward-auth
      tag: v2.3.3
      pullPolicy: IfNotPresent
    nodeSelector:
      kubernetes.io/arch: arm64
    logging:
      level: trace
      format: pretty
    logoutRedirect: ""
    middleware:
      enabled: true
      name: traefik-forward-auth
    restrictions:
      # restrictions.whitelist -- Only allow given email addresses. (Comma delimited)
      whitelist: ${SECRET_TRAEFIK_AUTH_WHITELIST}
    lifetime: "28000"
    urlPath: "/_oauth"
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    authHost: "auth.${SECRET_DOMAIN}"
    cookie:
      # cookie.domain -- Domain(s) to set auth cookie on. (Comma delimited)
      domain: "${SECRET_DOMAIN}"
    providers:
      google:
        # providers.google.enabled -- Enable the google provider
        enabled: true
        # providers.google.clientId -- Client ID
        clientId: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID}"
        # providers.google.clientSecret -- Client Secret
        clientSecret: "${SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET}"
