---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: kube-system
spec:
  interval: 1m
  releaseName: traefik-forward-auth
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
      tag: 2-arm64
    logging:
      level: warn
    format: pretty
    logoutRedirect: ""
    middleware:
      enabled: true
      name: traefik-forward-auth
    envFrom:
      - secretRef:
          name: traefik-forward-auth-env
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    providers:
      google:
        enabled: true
