---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 5.2.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: minio
      namespace: tools
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    timeout: 20m
    remediation:
      retries: 5
  values:
    test:
      # This is a workaround for the helm chart v3.3.0 that does not support running helm tests without self-monitoring enabled
      enabled: false
    loki:
      structuredConfig:
        auth_enabled: false
        querier:
          engine:
            timeout: 5m
          query_timeout: 5m
        frontend:
          max_outstanding_per_tenant: 4096
        query_range:
          parallelise_shardable_queries: false
          cache_results: true
          results_cache:
            cache:
              enable_fifocache: true
              fifocache:
                max_size_items: 1024
                validity: 24h
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
          grpc_server_max_concurrent_streams: 250
          grpc_server_max_recv_msg_size: 10485760000
          grpc_server_max_send_msg_size: 10485760000
          http_server_write_timeout: 10m
          http_server_read_timeout: 10m
          http_server_idle_timeout: 10m
          graceful_shutdown_timeout: 2m
        tracing:
          enabled: false
        memberlist:
          join_members: ["loki-memberlist"]
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 168h
          max_query_lookback: 168h
          max_query_series: 5000
          max_query_parallelism: 5000
          max_streams_matchers_per_query: 10000
          max_entries_limit_per_query: 2500000
          max_cache_freshness_per_query: 10m
          per_stream_rate_limit: "40MB"
          per_stream_rate_limit_burst: "80MB"
          split_queries_by_interval: 5m
        storage_config:
          aws:
            access_key_id: ${SECRET_MINIO_ACCESS_KEY}
            bucketnames: loki-logs
            endpoint: minio.tools:9000
            insecure: true
            s3forcepathstyle: true
            secret_access_key: ${SECRET_MINIO_SECRET_KEY}
          boltdb_shipper:
            resync_interval: 5s
            cache_ttl: 168h
            shared_store: s3
        schema_config:
          configs:
            - from: "2021-08-01"
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
        common:
          path_prefix: /var/loki
          replication_factor: 1
          ring:
            kvstore:
              store: memberlist
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://prometheus-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist
        distributor:
          ring:
            kvstore:
              store: memberlist
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          retention_enabled: true
          compaction_interval: 10m
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist
        analytics:
          reporting_enabled: false
    gateway:
      enabled: false
    write:
      replicas: 3
      nodeSelector:
        node_locality: "internal"
        kubernetes.io/arch: "amd64"
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
      persistence:
        size: 25Gi
      resources:
        limits:
          memory: 2048Mi
        requests:
          cpu: 50m
          memory: 64Mi
    read:
      replicas: 3
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
      nodeSelector:
        node_locality: "internal"
        kubernetes.io/arch: "amd64"
      extraVolumeMounts:
        - name: loki-rules
          mountPath: /rules/fake
        - name: loki-rules-tmp
          mountPath: /tmp/scratch
        - name: loki-tmp
          mountPath: /tmp/loki-tmp
      extraVolumes:
        - name: loki-rules
          configMap:
            name: loki-alerting-rules
        - name: loki-rules-tmp
          emptyDir: {}
        - name: loki-tmp
          emptyDir: {}
      persistence:
        size: 5Gi
      resources:
        limits:
          memory: 2048Mi
        requests:
          cpu: 50m
          memory: 64Mi
    monitoring:
      serviceMonitor:
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: true
