---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.23.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
        grpc_server_max_concurrent_streams: 250
        grpc_server_max_recv_msg_size: 10485760000
        grpc_server_max_send_msg_size: 10485760000
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-12-08" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 30d
        ingestion_rate_mb: 50
        ingestion_burst_size_mb: 1000
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_query_lookback: 168h
        max_query_series: 5000
        max_query_parallelism: 5000
        max_streams_matchers_per_query: 10000
        max_entries_limit_per_query: 2500000
        max_cache_freshness_per_query: 10m
        per_stream_rate_limit: 250MB
        per_stream_rate_limit_burst: 80MB
        split_queries_by_interval: 15m
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 50Gi
    gateway:
      replicas: 0
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      rules:
        searchNamespace: ALL
