---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 3.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: minio
      namespace: tools
  values:
    replicas: 2
    alerting_groups:
      - name: home-assistant
        rules:
          - alert: HomeAssistantUnableToReachPostgresql
            annotations:
              summary: Home Assistant is unable to connect to postgresql
            expr: |
              sum by (app) (count_over_time({app=~"home-assistant"} |~ "(?i)error in database connectivity during commit"[2m])) > 0
            for: 10s
            labels:
              category: logs
              severity: critical
    nodeSelector:
      node_locality: "internal"
      kubernetes.io/arch: "amd64"
    config:
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 24
      ruler:
        alertmanager_url: http://prometheus-alertmanager:9093
        enable_api: true
        ring:
          kvstore:
            store: inmemory
        rule_path: /tmp/scratch
        storage:
          local:
            directory: /rules
          type: local
      storage_config:
        aws:
          access_key_id: ${SECRET_MINIO_ACCESS_KEY}
          bucketnames: loki-logs
          endpoint: minio.tools:9000
          insecure: true
          s3forcepathstyle: true
          secret_access_key: ${SECRET_MINIO_SECRET_KEY}
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/index_cache
          resync_interval: 5s
          shared_store: s3
      compactor:
        retention_enabled: true
      query_range:
        parallelise_shardable_queries: false
      query_scheduler:
        max_outstanding_requests_per_tenant: 2048
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceMonitor:
      enabled: true
    tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
        tolerationSeconds: 15
