---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard
  - helm-release.yaml
  - prometheus-rule.yaml
  - ingress-route.yaml
  - certificate.yaml
  - config-map.yaml
