---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      version: 1.0.22
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: portainer/portainer-ce
      tag: 2.11.1
    resources:
      limits:
        cpu: 2500m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 350Mi
    persistence:
      size: "10Gi"
      storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: "traefik-internal"
      annotations: {}
      hosts:
        - host: portainer.${SECRET_DOMAIN}
          paths:
            - path: "/"
      tls:
        - portainer.${SECRET_DOMAIN}
