# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    SETTING_SVC_TRAEFIK_ADDRESS: 10.10.10.210
    SETTING_SVC_XYZ_ADDRESS: 10.10.10.211
