# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/PynjzmQg6CYbG+a,iv:eM0EBbhE6IOghJlD9J9l7pqsgLBf0x4ElJmA3wmzb7g=,tag:2Z3mgWC3TweDCubHIjPVww==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:B9qkPDBqCnjBdurOwfgEw75LHywASRBa42Sp9ly43An/WOgGCCoYs/6Gv0nLnExf3h6RDwiZk8q1qf7TLKEEwq1Ug4V1C/95,iv:F4QsqkgIpz8EZVPgCTMNrjXAA7iuXjD33qU0Xta5VEI=,tag:pH1AcsXAzkpHNByNE/5NHw==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:29+W4oH7ZVeI67xLa2Wx5oPkilFB/6qa,iv:rS01XNTZx0soPOPToEd1jWYldlHVgcd1sVi00U+JiyI=,tag:O3ZX4GyhDq9hdvk1O89GsQ==,type:str]
    SECRET_TRAEFIK_AUTH_WHITELIST: ENC[AES256_GCM,data:YnPKTCYiCahH0luaQZKZWiFJAbsA/11uOCwrR22FXp5R2TKmLYGtTd6lEwqsHWwGgiPZlhWblWdvzh6Kut+68GtjEIjJUvjQsScaHZhjhRz41pci2ubhuqSaG4YwgexAtXOpppw2D6lh34vkNiswtW2SnmNfhoM0uxOi3B6pOYaeAvyhxMKASI3l9QegrOX1enEvEmFw/A==,iv:3K1p85zyMXS9FFoh00e2puqLhkERNHuaM2T1lqlk01A=,tag:E0ai9+9u1aiEPM0cjgvFHA==,type:str]
    SECRET_TRAEFIK_BAUTH_MIDDLEWARE: ENC[AES256_GCM,data:g9hrXqBjXi9QpUeHdMwVJvGH/qsIolNJy2pmvYwiP0rS5/SLiLpcCZWSvLcbmfg=,iv:c3bWpjIHlm/thjpDPnRQFRm5PchtZ7ZmxJ1mKmghwKs=,tag:W8tyfLv9dPczSxQR7cPnbQ==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:gKRfFPR/ZVM6m3DytbpdptgUcdiARvEtKS/HwTkPW+VbML4+,iv:eQR4RjYLoKqqO56yub54h5v+qW6M/erF13LF/mvohLY=,tag:dvbG/HvQgG+5McvDEC3n6Q==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:F0x7VbLxpr5JW14=,iv:Nqe/gzUxOfRE9Aj+FpCHItDzlkhRQwDjd159xhBuyEo=,tag:pF60DFGgg7Y/toeN4J2JEQ==,type:str]
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Rbjn0qV82BoqogE2mZoiteuoF9LQLOhM4FB4sGQbg8oo1HasFLbnU6Pim9bxVHKBmL1oipGdpT9KuruBkORHMp/2TIU/pRX8,iv:raFkIXsX6+L8DCYYB5I9Gko5wMLo9sTMnQ5pemPyJsI=,tag:yqniNJE0MqZOONeLHt07kQ==,type:str]
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:rIEthfjunQVYXWkrtSLyJVNruLo3ZGqB,iv:bSskEUxRLeEbwtmM4Dko70k2cfDo2wo1XvRQxGDqwPs=,tag:7Zal0fHp96V50n9qrT6jPQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CJvUOEdywwYCkmUfr3zlPo6q0hOnYZub7bGv,iv:etCYjhBG3NoFUEaWFV7xTJIBslRdf7sKXOmmTIfkLw0=,tag:3jdhBQf/YaOwqw5AlTEN5Q==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:6lxq8qh+9VtaKbKKjdXxTEdLxfNjd//LK9BauADgPJk7Chk0ng==,iv:otd9FBoQKAdQkkfRJqxJf7S0xpU0KNG5ihxcwtPWYB4=,tag:YoIOShQ9TD0/TG4tGBFLMA==,type:str]
    SECRET_CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:VmDcGKhoqgMrkQ+FPZTUopdvhetjicIi+Zpwcbq8j5Ojb00Qg+W0MA==,iv:1qlEvoXNUKihduDLozY4k+JBiBcZ1t8RG1j2tHVcjAM=,tag:yk7SdrRk7zpmhB/Yf8F/nQ==,type:str]
    SECRET_CLOUDFLARE_ZONE_API_TOKEN: ENC[AES256_GCM,data:gAan8AYg8MQFbqiNTrPaXsBcVIVTYuEuQh4+1waGbNItk9IjYgqxxA==,iv:alOWiqe6lyFeNcDTkSM8nrsXl8l2aPz8hclfACCEnes=,tag:emEOCd9EYnneSumkLTN2YA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:OU0cPf+oU2JTHdf1jwMPCBxStPPLxE4udYC7KROm8wGtroDFPj6Z09Qr17fMrZL4uTTEylY4v8anDaV7Y9rrypU4fhl1ZLuuTrvWm2AEJDcHh5rCPtQ070liCZkmuhwGFTopTcMM1bXSkls8fHBre2ieBhHijGQODNjf,iv:Xka8IylHnllQFRWT8IlTL9cGQ2Mmh6SZD9l+sRgFNhM=,tag:a1Zw4D73L7/C/4DBcsMNTw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:inDLn+5xhQ/Jw0yPIJFJ8qkDogbsyG7VA8Zj4SohIw7yyWB20FfFaYpC8xo+,iv:orpxKObJOWcWKVU6qZAvdnuPE4Krj2DXxynDg1yTu0E=,tag:Ay8kTSuyjgu3OUrN41q8lQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:zOja+AfLDOFDZnSH6xOir1323tcsJB/lY5azE72PHAgPT8XeCSxVZHbjOgi4,iv:SPxNqv6EEOt909VNg4J63Cc7D1rfY3OkCTqmoKq92vI=,tag:3cS4magQVW/MY8w5GchTXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-09T09:50:58Z"
    mac: ENC[AES256_GCM,data:tcza2p74hXQFYzlku1xkU6643iZDf3bKIIXDs9vWVZpVKB3VXHHdBWPzt4SXuErmJ5fd5KTVXResQ9mDvbBn1cHcSXcT4rWcVNCRE7ZXpes7HVMGleDLVPdDaofLtyoJYkNMQfXSBGjHR/KF/22eoEiQ2xhO0RINjd5d9gmJFaE=,iv://RA2++W9LtycH25gm6PGx4qyB5+SihZO5CfRmK5BC4=,tag:6LZIkbd8iTGNObVD9d+yBg==,type:str]
    pgp:
        - created_at: "2021-07-04T14:47:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3t//ZLkhd3HAQ/8DT1iTPiX8ZqEuWf7BhwbCJmYIKuxsiGwZADGkzJKts2h
            pP9FQ5oBso232SxUfn+sepEYHjQOv2uxwY1dVXr3+T8DWL8z1NYJWQ+ftxStSdZH
            LOW1HbGtV3ee1HktpdFz6jMNuUnmV5KLjK4ADAbuPSVY5BCHfM7N1gxBFq4vlJYY
            ujP2QMn3o6zTo4buwzpQmVJz9iRYu7CUI+IXyuvcQLxnvNneOyeeVTBOw7jyBhWq
            srmyidD81ipLSOnTra/K1OPloi5ukNYMxyGDz8AQzuxkjrCAKKr06IvR4g7+FXPD
            IrhGB+BbfbwAfaK19la5jzCMDHG+yyRngSwXY9LJOJoI6RkgF5XlKHa8u5GkXlrN
            SOp78DvVEifUhGxdLht/ikWStF2FnRcC0fZx55hGuC60+dnKCTju9Zwd8dHYW1q4
            +FQoAGmIyVMNMFEwHHZ5xlpEHdppNvwFHTcTaO7MBJv2qZDEoRrs2wkVYGD7aAtk
            ER0oNR05qt9Axd/GyU3UEezTjWyo9Dq9UgYfnwALF7mpUiWB2KHpWnPZPgg5stT6
            qqs/8n/0tICPYG9bL1IZdhTJ3jYD7LlenLag1l44FQo6TMunAaQ2YcjEg8ueww1b
            PIXfRPfSTvOfZB60xMKhEqXK+QtubaiCnf/0jQpikpMy3QUxp/n965HG/yl7ymbS
            XgGH6Hgl288cD0thDnZQcav6GpvSJ5grb3h3wwlJKo4SDofFP/HFw1cQBPcH0v1a
            eoJOPYfObMNS6aDNPnixAb/kKCYE928rEt2v4YbTOMVt73qFqqYqcZXuBLlE8rg=
            =3lCF
            -----END PGP MESSAGE-----
          fp: "0x2141D0D63053C652"
        - created_at: "2021-07-04T14:47:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwMklZWlTgvIAQ/+NYVWl2IYbDjluxuzq9xib1jj+m52YRKXabD6CKlaxGv5
            x1r0KmHZ/taszJSI3FQfZxhqh9RSDlln7AFFusDygWlkmCGH1y4pwYRsAEE1SlYT
            VZNuttiXxqfVF1CTyblFcjoAdNn5gwPEaU5TI/bDQoYamy+a56IfOvlrMO8z2aQj
            ex7ABXtNPrTnongdokHSPUGhwfG4rRgUnIVbjHHtkurahnyVRlv67i1yyuXFibKQ
            MshhtSm+hVMUzcBR9lzFx0fiMqNxGFMmkBN5GO8EBIiCiNl31H4Rp3I/JoIGnkxg
            vGZV9klDVAHLw/OkOAmklZccka8u/OvYUaYIu3o+Rp1J9hISAn4ZtRoQT7FW9JgX
            xRxgUAeaz/wSY88gkMCvdw1WyKxAg46QamvsndyAdjjw7kL/zH7tc68Jz80MZ3xd
            WHE+BUMDcZopVGcTNEno9j1DPete2lwvRdR0FaJo1E9cjLdDzd6c7FFDscNrurME
            eIvi7stDalAB4SYNZl2Px6GSG+LGo9JZSDbyEWwnV1uFvWgt1NI6fUv1AqKn8ifI
            l1jkCa1hP/xno0dReR1BJkFhwfkUSD80hvYbPLY5Kx1h/HVGBa5uxM9BKhRHj83q
            ry2icayJVz2IYFG1qdEGrtGSpiPoqssnlCHk0xQ6pyosg41yQZhpu92RsOC5i1jS
            XgEQ7fjJGAv2wCrw8xRtgYY/9gYdD9cY/QHhlBCkOThM1H9zu9+cwXNd981ZUUsW
            KgGjR4cbXgHoUQ1ij7Yh0/XKWTb3mf2McpEkwOzncTQdNJsBFXOYhPmuUFOeMZg=
            =rG22
            -----END PGP MESSAGE-----
          fp: "0x03249595A54E0BC8"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
