---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
