---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password
  - cert-manager
  - external-dns
  - external-snapshotter
  - kube-prometheus-stack
  - traefik
  - velero
