---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
  namespace: networking
spec:
  chart:
    spec:
      chart: traefik
      version: 33.1.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: metallb
      namespace: networking
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    force: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.hostname=${SECRET_DOMAIN}"
    deployment:
      enabled: true
      replicas: 2
    globalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
    metrics:
      prometheus:
        entryPoint: metrics
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    service:
      spec:
        externalTrafficPolicy: Cluster
        loadBalancerIP: "${SECRET_SVC_TRAEFIK_ADDRESS}"
    logs:
      access:
        enabled: true
        fields:
          headers:
            names:
              X-Forwarded-User: keep
    ports:
      traefik:
        port: 9000
      metrics:
        port: 8082
      web:
        redirectTo:
          port: websecure
      websecure:
        http3:
          enabled: true
        tls:
          enabled: true
          options: default
    resources:
      limits:
        cpu: 4000m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 50Mi
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: 0
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
    tlsOptions:
      default:
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: false
