apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  encryptedData:
    address: AgBE10cBtDvHj3trWzEu6SN8wLkw7DjQpyFdjI2U79s8AnlODHWevXadpI69Pi/968N/HGGB+8HUSw9qub7pWV993s55WvZHu9xvKjM9ezsI+7UhYtOEfQndo3MxKOFDW0WT71yxLnuyp64Wnl82OKC7+IFQZ7Rc3/U1rOcvi9KoPq5vRQjKnz9804U08RBnay6MsPHUyKJcbtyODzAsUl2fWgyP7za+ZX2f4Xl+z4f48anXmPkNdlPmZfrLKlfpPkBQMB2GRsqLc8RTuojssk8YdUxOaxSE2KuwS7p+coPoIUHtCR3975Jih/6EM3e/dAE0PJ0FWxI1Hz4ey0PozIyfu/EsyExmDfwrpXtphoKakKq8fEo6U5yKk8nKu7vF1o7dY1BT85yWVk37qnCUjrKy1SE+kJvsl7YlOXZlX6EjX3sNTby6MxdbFSDy/Za5F/7BPz5WSiFVw+ZnpNYPingocgqE2iN7B6WTCHHwvagAKcfOpYrWY5erT6EV0+VSusQDWphZ+HqDDd7K2tBYhprwBAwqOB/dbTBrnky7lkZu9tC3SDPB7ZT7cmxzvs1xtrJ/Xs1JcrSSov36GjTatoHAssZilJOKyGUY/xsvC1+tERmkpSk9GHZgCxFuqE4wZNgsan1iAttgFrT6It5PqKzTNIE79yjMCKTrc3zB4UxreIqp5w4Grk5vpJl3c1xsjTJRCa3IFBmbiY4RHDgLXl4mSXcJOQ7CsBZHY74ulnNGthhIjId3DGXzjv1stUJDq7P/8u0qIXH6e79sG2r+iy/QTC2PBfBrbY1BDwILJhtYB4lK5DvFjk33PpcPCOYkrnq6cvuF/vPgj/OBk12DLYhs7S83oW2g5+I=
