apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  encryptedData:
    address: AgCBAnirD8qeaHTXe+OC/E6Cqh4Yz3AbnwXFNUXTqjAPtsj6F1R1swjDAmyrk5x5SSYUHpg+LZmhpAL2fV8N/z6VmYM2MzRD1RHlxi6aSSTjdGHzeIAbS7gZHXO9tO6hSifCZjnDIwsPVKRCrFm7dpbQcDboehhrezJabN0PFXF4JZ3upm8XZihPoyuUUTxYRfBHg+RV0I2vqXqT0f3kOr6OTGIDUZ2eenKhF38Hx4SbWnmUf7zI4j4a+Kw7xEg4AjzHh5giEEsKLxgQ0E516c5FGaq5aOjgx+sjNmaJQhXziR4U/21ZXmgGjlBL2eMJtxih/Muw+m3O5sRC5TkaCBbFuc5hmqSDrqVA6Y29PL60POhS/Awhw7r5IDs2TYCHMZ9laZFm4xWtwUN2oUfca1XvLzmmYT38j1zlTAhmanrmODcrecYTqozICIAHSoxQjClL+05Q4tWP2Uh/dk06HBG7PRNMq8T7nRzr96f8PoTQYHMLaYkioRzUzeQM209ektsY08C0oVelxg7z5FrEMqPs0AXrUhDsIZGIQMfyivfjh59QvoX7e7MYL2t0ZD67BtBwCHDyET+LQY2FpTk8xrkbCJr6BKLPL7JobHVNhQmkgrtcmgCMlruQPn0Mfsk49F4bhlhPRbe/m6HezFqbLgj8FgIfQTVYIGFilRmxIT0otg9M2K+gStyJMyHQxq3GGyh3HFjzPgRl2Fuxtweud/26GCO+FP9M/SYqoFUbQ8xTj62Z3qkZSW/iF93IN6BehsSy1eS+S0VMUWwbqynRtl8AApFOg1yfsD2kQ+QIcG7fcIEERY38mLyNGsAvs0NY5HfJICWJ2k48GPn/QqfdGDtElfBH60aWb40=
