apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  encryptedData:
    address: AgB7XzbM4bAnZAbZ6kyFLbadXiJFEhwvp8j+FOYyYx6o+W5CPRgNW3EIF1s9w6hLfTIJG3iCkX6T34mJkhnpTbxW62+ZaBpY4bZx0BQaaOyLlX1v7JPwP4IJA9u1czle5/OL092GVbMj1OcpNGU8uqEtdcw8Bg6JLWtQEUiQH/YkcREHkWVJk94LVmFn2jlhZQyra/LThqauUWWO/iSj7ws4Q/pD/nQu0/zaTe1I3b74LoDgwideA1CETTuqGMamS1AXC5tSB29nVj267b3nc5MIEpE4fQ/jpiG0jcDDrZIzZ8Cd4Qz5uSuoPZ0qes1g+qWd37tC2HtKwclF/ZP0KNEdtJYkTaLaPkCVpPUw1BdVUBYumkt5L48PD8yMqvBAmbMWugiR0fGtK5Ldl1m6Kaf4If5xYbX8SCJHl22hGemKjHZwGQEKEGoqKNxamIKxjEHsS6dNC6merQMPhXUUMaJxHw77czFb9GmwzsRlr2P/mPUKXYsSMoHlmFGnZYLvVNTqo4D8NZ1XW/vrEui15edQ6OZipk2a3hlmgyP5RUMSOSFmaeET/ek5xhhG1r7yEo0Q5M92mgk/bbjIq8cCzjOFx9Xz9RswBvBiHpo5GcM++WYOwvOZLwi1CSYZCs4R36RACqnmXCxBSauI9nSUJQE0Xzh+XGXUUUpQNeV0U7mquPd6536FO4ErHM73E+sSVQVN8cQnaM9B9C9h+bNxqpybkHO41KhmlbyF4TjhvKoPMG3ajNSFoZgBk68i2rRVfp+kO0J/ShHEKZsX4bYcR6qYXU6sIPYzl//9TpQth72uzAIjZW8W06T0ROCcu1UXu1jS75ZH1CXaSRA65DhbUwW1f439rzGcBrs=
