---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  encryptedData:
    address: AgAPRpT5BA7Qh9KQxsm7qKXnxbY4KsS+1A7f122SJGTDcSw/bD+s48WwNLLFcjX1VSgphqdgVcRqFrSQeW/htH0bR/RIWpQSOOCW0zyyJBVqZSeLIKORmdeKbk4ajPS3MHIp748EjK32zer8lT4zYWtNKbQVk4OZ7Z2fdAtyiILQjWS1qHT6iRVRSFwPBrZHt5D65/SD6HPBE2xlGLhUUmlFnmaIPTJiVBQ0BUy/IfL4VikcJubNNPifUA01tkWBJkZzQ1PiPOzG7c6hDScME/gwSSzC+fxBNHDIzsmAxqMoQB1UenvOjebw6+G6ryQRldB3ftoncaBzZtPQcLQtrSmka2586htFNbUcucWAFZG64CoMVJJxPrrd2Zs/2ZVNl7d9x7Gb2ZgNcV8/mNQP66JLHbMDl2P4OAj2KkML1XIFzmjV4Cl3YR0c+rei5Qgv9+5AYnDVNlnn5Np4oMbbUaj2KCw0e2QYxqvnMCQEOVzK+kTMWp00UU1TokMF515WQci/KjSFV0etXHQ/R81uRWteg0ZOAQ5I/Ncv89bWeyYT3lkANJ5QLPSzWQR+WNe4WQjQIF4PD5SJG2qvb7ulKFMctWHI782aDnrL/5u37/P2wWnelyleWlTqfw5HwjrD+W9HunshdFslIh4v8rP+0XEmtQCx1+EW+OZ89nDhDo6Xbgjmttxji+f1N1HEflYowPFeDxhE1kxAgpwsG25D9W7LQwCHo1jY7KAVPQ3Jo3QoRZmEBgZ8Cq/Snb1kuuNAMv3/n6KEBRUi3Ac9MGauuuLeSHGx21SHcafPmXWVjzmAb8v+I3nvPkAEg33WQ/jgO7V6JrxXLBODxxmg3ptiW88VNVzRSYd2miY=
