apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBG+hDf4k6CytX5BRy+MSxdk2iFVpA82F3IuGSMIcdADTR2ntQM0mqt5pdrvnbhiewT+teJ6n6NESqOyV2DzmNp3w742vY8wX7nw8US/o9A4uZlXMuSwheBtPum435dsk7F5Spk1tOaqbW24vjHN2+bLBHbVLpIxiYAirVsNqt+onkSD8iFpGXtx+fU/efpFvCvBfeBlOxi7RPdnw6WyLt9NNijf208ibibI7H7irob+3B1KxJ542O6RjvZH72MOk9bdvTC9xfwBmGMq1/FSbe/5wSdxqABgO+qtwBAOeBH3rXXeaDBxlpFZafa2dO7MV6NzWce9VvwNF+XGwSWWKM5kILkd+phsKaKa8JOSFrNTRryFNTfPCKRjiepqdpfasknxHZUolEQV/TT0iHKCSQxA566OtPysbsQra/lhgrtGqehWIaEcbjbW+QJ4mOTJk6cgZ/wthugUl7I47Ntx4rZwgQrFKujN75Jg0w30hCtxnN9hNLhYCXmWhXAFgBPD3Q5Oh4sI7uPYP3IQ1BqG6Qpluwb2u8piRnKRVlwGVAqX0rUoRyWto5zIdJUhUuQj8LxqlopnxqbYhXVGyrn38geRshPFRxgPWzeeiVQES0btKe0uIjReSkcZ4hiBBgPiHcnSwy8QqsYJj19kj7BkJhkR6KCOhWZhJOIxXdjOSCOIA//4Vz8/J9NATvKi6oZaXo=
