apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCKZsKAD3YQgdKIYnnd6+4HhXnTRF5+KubsYS397Mp5ezcMiGOL7gYj2ilxdvP5KYN5WQTLiuwjKDpecwG7VOPAL2MSIiI1EZond6rjIqSQmQgcB4H0R0wRHifDDZa163LjWGJax0r3wYJIG7ZXkgNTMlJcGWS3B16fmLpNr3Jyq07a1OhQeGS7TNJJj7MJfrJAXMSxhteFdRdU9PJCj/e0zLke6R+wdy+RGnHm1vL7UVWrgV3tlMA7X+BlOGzx79Y96K4tnu5ZaGEgL5eCPvTwYyiCypeC3EvLieHwFxhjwnwMBLIWcfQtbf5ZTqcYwbIxj3u8WExt0BXqqLiKzq5V0qHiPtdlsebuQ02FkHcoCVYhTn6ChGZgsnplcDA97bYeie45j7D0FZ5CxGLJDlMNyjTLc0635dLMYxGXVsX3iX8cPILIh3JoGTfELS32feJU/r7WDmIs3J0mwvhbTZfLr+eGahoLYScTrvX7roFjYE/x7G8Cx9olo6h5HDPm3mQE1xrK5smGaMBdtHQfGpS/2X5FmrCXFGRVAU4qfyMBKbEoTXjtTONL4HbRo9wgCUDk+UWyt8W0dkQrVh1fa2L3KbBnctAWpNPtDHNw1OIzksK8j6q7vsw9FnAiczp7zg/f4SO2aIeet1o6Ho0noUMT0TFIZDRpQNax6/oeLSJb6njDBl0gKDe2vVNm15HrMZ25bYSRf65RBWn09d9pzGMVyG03LW7CCuAef3OpYDC4e2dhqj3BtYrtHLx/0IMxvCt9hstDnOKRlXbIoZ1iWdHPmZZbcErVvMNo/O7PU+F07c6iR0xhq4CPbRIGH/OFxpfYpGuerCHZ/dGsY6u+
