apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCehVomgIHYGYVMSg5N0qR0OdyR9UZOBjZt3dtYY430DxICyio3CQSkzg8bQ+/m1/JgvqZid6LGrCeTfnniUOX1NTT9eAzbndoZe9tlu8zCRxXvss8Qn08t1jkjJbQ/zZqyV+lxtVqQOeTbvvRXuAg7gO1+h00uM+fGxYbxF3QJ13oQERwcyf6dVl2JHd6+4zDn84vLBw/5fUJ7J+KB4fkw0TSRCFY7S2jLhGEahnLhZ9Dlqnpz+3rFXq3gSYFUUiUNZPeYYDV/q97z8q687eR2XwLyXgoL5/QrZbHFklohds+wrlCvUh9SSjQfZgCAaOhuh2LtihIBC0KWqHNKjiWjS7t47lXk6LhvFXtOVCbImixUIJuMfPPn7XYtXDZUHfyDpGuPPJKinLPzrr1Hoibp9JkYU4HZF3EoIBckjAa86DrafqhUwfFN92itHF+lWY/28AaAzgASfErxeN/WmWspT41XzuXlfOOu6DF4DvD9tyzoAByYW58aOP/b1URbvqdb6+NFgftkmJtm/haRm3cXZV/HTtWBezTnTSEKDFPm8cee5pnpZinaBDYKzdQ7xb2L+fggDltMLJOzURAlIXwY1c6vP+V/d3I1OhoZ7S1NnooDy8EZamnyZlwaqV2l2ThnSMpsNMLcJ6IJlFHdgbkyCJnCIu+ZH5DmoKzd6+ahtE839CWI6XIx7M+ca377/a61zbQGAinkTvFAtFPTeEnwNkVfvSc3bC+7CCCQKjR+8eQomtP/y7Hahzu7EEQNwwAmGH2v8Xm10BGMfVLHU/EisfoVLv3yMOXeLZINn3B/MFS72HJXZUFeblgHxpS/YYGXsZ9FwCgH6ITiaXks
