apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgALF5eFLmG9cDolNjdOTrZ4gtgkUm9KJx3bB5H2WMZeHIJ13fFZaOCsaqOKhBFIUqIykMurWZvsFUShexEHG984dGjH+oe2pmzUKBhZLk/O5Z+29dH57ncjw2XyGQe1kDt72HHOCdYcW1OdQ4Eyu5fiAsM5z+gvc7KQXKMG1fxtqoJfKhOFyvnL5ltxBovAYQ74SCy6IvMA/cPo2lXmqWaW4H7buAB8DpQJSxbpRFh1fr+KrDKpuh++Lkg06aImT4eAdJcIxuLStCnTbK9SZfWWk9JxzsJ+C5pL87ZThhW5WxZGJdP1xHb2uFt++KKn1//GfH9ldpQDDPKQz84k+fWAqtDR6pyltLKyKxhMA1IbzCzBugNmGmaqN/43BHkQ1ZGjF9+fYvaFew9A9ECXT57XJEzXwjMKfeuyw3MaeiMsaoss3ZL73erRSuhI3atPQyd10EKc+FAonCZaXmTVp2yN9OycbSZ2cs9qE3Pjk/we3xxPJHwgveEgTOhqbDv3eAht4E0xUfXZWewKEWZYZlBnckVJtgXQoggWgEZ4DKXCj1KxY5CtdPjqQlLEFQDwnOB14sPkaeDDtDyUq8Nl5aUJ2GFYB3xUZs3FS5/p7t+VBQ86HwL4tWYDJYVugkBXbq5HQoSmwsT0xIR6+K0p99e8GeowivksYnsG3MkFsXk2jbOkDJ/cVLOt34x8U9IAxpAErM+B3gOH5bFdt6c22+Mv6RSSkQ6VbHwL0scBSpihQa8DEkBtftnpg3TVnUtZ1BJJr5b84xUyw0w8LMkv2XChCQNSUCwA+eO5MlZMcwST6+1B4ICaXDZo1ZS1znRhClml27KeCwIc0DBVA2s7
