apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAL+JKgbtGFudH/Y48bbyDx+FMMbMGMruKWY186wCN1H0V0q81J1l59C4jEOq84+OJa0kY9thysIMMEuLyWmZ1Bt36Ng9EBfCbeFDnbD+zDeaDY/9U5yeKqvn+waPwOldFUTonZw0mwh38b0BnENJY/ywM1iHGtc8NGtbYur91ilZaPC5+cjMZWASa/jF0I+xHUFKFuQqSqkmPqpJA0vXIBWXLwPGRGYuI69+4Q2nUUikL9xlAwjo0AbmSYwuxt41g8ia3epF3kuck3GZlz/C75q7SA0yg1TOt+4W66z4D8sImMWc6zbXGOb+kCxY4uuB6s9woGbcuIRiNjT/Yto7xSgukDKZYBBfucrJPMu0gEy3/GhSCNhWiSrf+30pe9mfSeWV4Jba9x5JOuOkCkG3/I1a92Cf7E0uTSRnEDd0jh2B/I6zqaoUpa3ofnFIyM9d+fiOrTrX/I116g7lAFcejtUJ+wsG/ZEVDMzhlQPBLbIjnFNejkKIM/lRCyCqpZvtUbMfbjmlXe60HH2YmW8bUgt2qO4J0hiVq2s6J6RxZg+KhJOiOTeuda9tGfmyo5kuDPxU5PqQUc9m+sqdXMaayFusGQ8eXHlLnJ2+nwHgp6hr+6rOd1ag/pLp3T+JTyWsHkE8BMzrVkh0U1A1SeGIWCjUysj4cnVdFfRAFKkbSoqHuH+I2fJZ4OHPFy5+k9yFZoEY6KIfdL6eHPVSCBeaWV35b/LQbC6oV1LVq89vXKNgAXZqXmvj/fZnqscQF+lPxrK2WR8+f8BgFvb6SCZZ4SX0pb629RGL+Az/MIanbgt9qTSju4w+SAexy2i8sWYRtYVFppB9WL8MhB7wks
