---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCWzm/svYbMDB7rk5ehwZ2/fDolnkmIr5RjJ0xzDCeZ8bycjLDdBaRZ9eMnBuzwPvtOS7itwQH+u/xSAuOq90oGwk1wO7eDdzazE83jHzdV3TtIYt6V38XC+ENo9HVvK4X4nDQ2uMlT+sunFBeNUA1D7VEERQOWktfT8YCk/DwPAnS0MUmecvPY4AqEbnZ1YLRGxmrU/PzJiPDsRqauGjPmyDvsuf+gYskx00fKLzXu6fDMk14y6JiviBv7DP+n7bixUBTpTu9jIshvjy4loDGzXzQx5s+AVnOW9TfRRY8VXrtxi7EZmPZ3N6evhtTnmQQKf151/YSN+u3TIcPeenm6niEGsI7NBhEjE6ggbOpH5h4pCRfs0uJ2BZAjwsG0R+MuHeXS4euIMafJ0vCQcuQF7a4YTXE5Lp1RgDS50TzqlTVCCKh9yFr3xpDHsXWd8bWEIIN+Y85kVoNDxnVk/ok4yH91f2pBwStrdSXQjYEJRJM2Uk7dFQUIVfG3yRoTPpoxmrWjmUHjxBvmteqBv1yVU2cfgYzhvsmoLwqiOxQyW/mv6jriLFr5WeMlceGz0dTuWfAVKbAm87ZF967qNQgxqZUharuUDOGqsR2vInOVl2t/YMj4bwuI6Z4jverLmAFLxDBcEcjmUeP0diXeBwIwR8OTqWQqQcoJzoSsKiwQn85a5x0sk4a/x/PN/WWrrFwMyCbyY6dag0ACl5KNA1WsWUvz2FlpsW8Q2V1ldZcCSZ/s0DzE40aojhGSQz2C407lpj43iJ9VQFjgnYdiRr7q4yZmX182f+z3DDSuiR8AZL4zsQYQf2ejU3wKhQIxvyi0gS7H69Ug8ZtmeLwyTFOBlQ==
