apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCUXgjRN/FMYx9kSoqmahsBvRtqQtakrP6SQDl/NaGzdp6YtkYJcwAR8UooC7PiI7cQLcSQUkM6lfETp6tZrve/xXck6kRNvbbf/tDHhyIHpZN01E6egf0Oc6oYMSj5vWf5RAa9waTSeQ3X0Tk/8CxL4gf3ckPLuzQSxE7WGlofY0PvPVx2rPo3XdeI0KZExWPbo9U6VwgcVYv5/BWwHMJT74yBVanmVJeXjjtlCkzRv+KpQ6UpXMVVTTeFgDTr0J9OFjRc3Z/Zk6dYZMLTv2aXXUiezupcZbHrBGEmPJEG6UVR6RXzqatD5APynRzkAnea2vUdQemA094BVWMHlny5vPevQRTwQ/hSUsRElHQl9lQmZmjD0/5Nzb3ZYPcEyWiF/zN8lUqgLKD8WS7/+qMJchHK4FvRhcMztTv3i3f8i0hv18Cnxx0uCUMAOAEbRll7OamH9oFWUEbhFoVZ42CSvW1G5LuvmxUMDdMZON1NZwFkA0pXNnKj/uR4PmZA4Cq5Gt5jXZgd/ATxW5ly4NAfMlQ/tvYD8TsDr6tIoscRHnJYqCVxdhR6K7jnneGiTzs59wB1KTXGzo4x1I4Nj8lIn579fN6CjVdx+zPSpqlq7CisHNBIUX+pJ8/JvQOeD7zePZJsu4cb1QhyuXFmZ/lK1zWkBNCOD0LOlTTXfVnQYLjoVhcSTz8YsX96JZ5Ss18r9kdWQhaZZk/wOWTSYlE4GqXgDwe4NMGmjFCwvca4xhcXfPEs09e9X5ZUC/INDTveK3K/vmfTGN4O0rjd18u5rs5l/XzYLEandx00cwF1v6MU7vzr3zYVXuS6mNPiRYBec950O+p2rtYFL/a8
