apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgC6o0GZj+r0cEwskY9Y3AQMQCWxfco2euApM/X7Qa3L5HlA0v5Rd/yHq0J715qRMs21JNcypaWULMQGq7w4vq7Q+jYEjzbyMZQ6Nbmc4nDBXKpu2D8tVwN517uucNeR2A2iehtYUlN8SJ05LmK6gY2GpPG9xu0lCEaLC88hKLJnWiC8PDaZ7tEOVFRMp8CoVWRMSn6SE0W//cqiSG9zxvXQej0pRuzO69tjT6ByqH8v3O/gXp6HAwY7CTTKXLKukWsuAJMMPN+vEKGXakpBd00qff5+SGstfNPkmILIlqOy59mY5+vi/nLC9oFxCsu5Nmn1cjn6Zimnc9q1LxqrF3p64Ve6t2OPB5Zo7UO/9UqTAInhi79eODpsfYyWj9jrTAGjyRdL9hu9B7OLeOmoeV3QS0eViqlDGCs2eSJQv5UKp8BZbSzp5qmYBGJL8SUqL5XaitcxMEX/MZvM64Ad23OOuJDlajtX5j2RVUIKMzBUy5VlSiWvik9fMsz7/W+bL2lAaPUl+mN2O4IptgYS3gjST1UOHqDwZvUt0BQCAY8un+IL+zMIoREOop6ODwslh/r/T4ZIlrQefvDXyM/BEldrimBwiKyLcialEPLRhg8rbHDd9Nzc3iMfw1AUG3rsbHfWoGYTkLSDOCiz1w9kmBT+WVcGbvz3wNKUJP8wOxxf6Mw+qlCoIz7VQhavb+Knl5iAHpIbSSFYA/1msTAcgtzl9UxP8KtYIVOrsN19NBqhHMPPqrsgRMEvuCcIZkVv2alko6FoJQ8aYhJCZIhKnoqi+OI8KviwVPtlaKi6av5kK/TCrYggGtZwPRJQw2LtdIVun+jxzElO8FHqTTCq
