apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCEidknmYvmoiNCnB4R54Xcrsd13Bhb4ogzndrYPDHziv2UGCWijWGunnpnL7LHBlmXtfxjHcVzKsYtovTnaZGEe+bCTES5iTtAFDeDf7Sg6o0r9e+5rcbiNZter9VzYMLb/fb7HQ2+LljUEhqF18eOk8ctkD1qZF2F8zNg43y/vXpvchZJNI4THpxOwutDJvxFzBfVrgA2bESma5fiLD89e8GqfUG7AywE3uw1xZh+ctMhkUEWqASL+hQhrPViHC5daO4G2T9iaosHUBxMhA+6VOVLjyKuxudCbCjYNTJh2IL6Dc0zqcmPy9uGe/9NV1BeLoUQtduYzfZGZCFkF5SmOFCwPfi5ME55JbX7qZNBEuOTHgbYbLxYFU/KWV+Yp9NF4CQnDXkwnzLMw1r1z361eohZ40M8k0lzzoo+/Fktg/0L4jgKHJwB8KIIxMN1+M1KwSO1MMP9TKeKuHfL/Z+2zww/bRVF6jN9nM1iRf+4WyXUisOkTvOxqB3pYgOGxU3etDIE/+wUG6WmG6mKCZg/0N+yQaPbqi0qP9PG9KNVjSfQ6fqz3eMur6UnGt4lHOO0KWoh/pmyTXFH2/QhTSRJ9Z1iUPLhGdOr/co4+inzHNrfST9u5blbYxMj5OxQ/pEVn3ynarAvlZZHIzlH3DF+naYNeMIO7MRpo0UpiF4ykXB4+2NVB6UpZ/+6VSPRzfzdfsPPtCLEVy0d8w6phH7tD+/fvfznCC9LmlELriWCCWyF3ejKfwnr0R/5WrVsZUcAXyf98se5VnU/4LGXS+7TqaxXGe+s6TjYdJRYdmVZcmfiz+nhgCAqR3zl9wvtrvE9etZQULnmiTHMNRnK
