---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAWiWmVjoQC54inu+Wtht4OUsOCScIMWfgn2GAYJCQEGie7xZzZilMKX0+jPSf1WtByCZj2UjmjLmZhyb2tu7pJnNUitcoLPne86NCKJNZmdOccX2v2ZlED/8m/ov2u5NFaEuoE4fYlJAy+2yArw9NfqiaMwswuTg8dkkeaXf4Zy+EbZGrud9aTf1l62VSIcdQ4RYbYqnxo9cPSnDQDsIZISkkVXzhu7GNaOzBc1Wbti3nB81LDskAV1PWboKXxa5CHTJjnvwkQgFJq9ZqjQ3O5sSxApkKpwMXpvLi7K14iCcv5N0ttUWmVvbaTc55qHmvdhVJMyi8o/+oEs/vMvwsKMEVVKLtd80J+wEPlqZJ7DHl5lD3TFW5Tv6uYSTYdeqb4GkysmmhBlS9ECx2FCjsra4wjoQo7icZfArnIih9AE/A2Xy7E70T3XC7Q/SVBFedjRrwuUuzE/IhT2ErDGM4pi762N5O9lfbXNlQQ6mVBl+CouNqLBPv3jlUy9wPKTPxfCCO0WEUGb6EoXN3E6z7FKm3iX2LNSjjKxTm77kWkD8m6UOaUqSavjZ3clkMHOLn/fwnXUaKOWLOGMufOmW1nmVK7Y2Ie9RIFVhKXKfaCHtaEcWXAjdcfUrzrWvie517RVnIHAt944vIth12ttvN0xccosvYdPd82lgvnDV6eOjO9Z6pw8Uw+PbcBcvueZc5565hA/vwCW4RXaLtVjNwZSasaPW6A4DKJPRHhpasGfwrEcGPZbdoJ0gE9H6jGA/ahdaJMI2IazRyViwm8G9nuUWXxTT4WbDKaRjHz0Jq42NkJEXmoDaNXxpTHnRsjmxBVlZcVsWbd907ASpK/Eu69r6KpODsvwce97bJe+djY42z/k87s+UFgqxX7M/Nt9XVFJHr0YVHX/QEHd3xhOXfcIybJWMwlPA==
