---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCPxIvjhr8Q1VqSR1Zg83EHu3lXjFr2BfQlu6tEJfbDYWh8174vP3UTtCi5bVAOHnjXDlrC4aopkC0fKbTPSkA66dswHC0ZJ3RTsdea+6531hTrEsVUWJbHp5b9HAtnqqMetFUkuXGkOic7Sk1xvAfQB4UB2pBgm27MWTilUEHNQiqWPkxeBuQSt5zlvdabZJ2avtOy8d19/QRUh876ZbhS4lgqsv/67htdAxxdicgw5DBdoF5FTLfr5X6Q8JlLN4ScZlYAc173QpCD1jGnhiCOP05lFphuNfAr6hPHpK2aa4wVG42DYQU6hkY6dyTI3nOVM9IvEBpTLEN3hDBPqE8wLLRdzS137dvL32ADHCzQsMUemnUO5Ry3vsUtOIbwGA+Omw5mKyTq2UDkn6v19+Ja5MzMn4z/cAvEG/Giyi2SP2rODEjAPvEywtLZtdJ/aiFDyKJ5CABemm7OOkG5iHSyGmyJy4B0pzJxBbW3lUqm+k/vper/a8EC4pi67o4y8JCKmyWZPmGJsR7FCXvWEfkkeiRTZupLAEeN4THW6btjpsoFaBrLizqZMEuR8wPsuoE4agH7+PDgXt9mmykTLqsaWV5EK/2snvtytcVaxjM1FeCXP1xErQfqVrmrrnObRdmFQDJMyUnzDzfzStNafJK9ioLa4HqeXi7PHqM0OEESretI6OvJOzrDpbRfnocF/ijMxbXbOoXjLlnbWxoUUFaDsnOx0Yaknu3vIGT8HN4HmEw4AOFrr6I1bEp1hmwRIp7FvlKQX08XPjfVHzAjUrClEizseMsh3tg7aBeVlgHxlYk0+8SFbuBn6tvFDinJd2pwEjNdnPm71O58v+1q/uGidL7fShow33bY7dqKfb8t43LfxrXa6f1+pHiCgb6CmhKagbof/0lUk2QSrPMbl4rsrQhdT2X8gg==
