---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBjAUcJ5uOM0VAmUdkd7k36QbvgG6WzO4P+nbDLWwC6qVAsKCtll0pDase68WXhNNVSLRN9B8iq828iT56ma8L2zr8PfZLXLxbzcXa18Wr9C+RPgGZEDsqyIxS93T2wV1xXUEETbVy7X1d/4iv6ip7RcDwnd5/+V+SsTRBZgr6woQzRmQNiFhAMJB/WnVwz5MCMHDD0qbSreTFMsR0vNIgWcfler5qP1nnO12Qhp/vEfjJ4oe/QzCMLgCPzYvZOItH93LqBZLkFoc8HmOicLsWy2TnEY8HETBK8QeIhxNu7S6XharWZ3FKNEW8BaAyQpSbFSZsjwqe0QP4MUtlhXvKneDZW/yVamJUY1IRMGNSm/xoYhadSifbqO3me66TBhPCfJdGUYS9/rXx55ySAX3hxcwJ2pDK4EgISGCnlbChmBFcL/jhtgrbsdXXbiJP/a222em9KSM3G3IOprcoOeKx+aCLMp+KpJKdPZQMnsHh3E7b91txriAPIdUB+x9dv5PY88xXnf/6xxZFBXd/INuFOEdVxr6vhigWVyXQwpa8EvxoPVXzaR2RDC0IfzFVGQx9yIT0JEgfeUXwFjhQEcDvqnhJ0/+IBzMe9aHzHu1hGymJ1SmEeigG6wUe72nuWQ3YffacJ4Y2J48cp3LW/R+l+fvbwpr5fOY249+OS2UlI/izK3KMmlZ+DR8Tzqma/thDlhqmXHOCwrp/03EUhPkQSz2m85xNYHz78Hf2+Q61XvWve6PbSGHJh2jJO0yZKKHoGNu5SvVDg/5jPKCi4/OplbdPbqUoxwsrdd2kdwAepj7E5bKZcpA2nGcj2mhwWVxSrYjIjCBg30paDMlQkAFpw7z4j9BjQisLHLaf2FAzKTpZJy31ATaOXSRTaRoUKp17+8PIF+1QVHb8D2/cRT9TR7My+27xtTA==
