apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBS0mTKpkSX4yznmngr2D4pviCeH84d5vlhRi7Ilz4fS65LzxfJv2ea9n/MqVkp/VXJSv8/jag6COJzLJVCZB0YljwjTA8BDVV4RB8ZMOcZ6YJkTfiFdxWlU6nX3Xfdoe60U7w7efks0IoNlVrCYLOqIFjLw9f/iyPkf0T0INCjRD7SrO8YtYGp5VSYqyuIfvdlX/SNR5ed4Y6xMtb0/BkZX8G79+lmv7i9ZUDUGtWaHKOqv8FLT5M3YT5XBZ1ulIYvsP1nZFSeZ+YU1oZ40bfP09+lfhGivCwCh36FN4xiWfzsKfeG3K5WgpUxZbZkARjTnJfj56Obi28edjdJ4nxWB7p8tRTWUwRvLzBALeO2iwIg7WzvMQsgktQPueo8bkSnpuKoRSjzPmeL0v/0H5vHl5nbwmHvdrbBSHU5BqyLsdCBL/6gEeh0xBVoLZxmdLk0At7A0pWtbfGROqoeyomR+8NPGJxGXu5NUYTCGZkMT1Svk2JtGZUrNPmHgyKs9mRiR9BTzcsGam4QeJhOTV5fCFnCCqf/6Fd9LuB3rU7w6rGrdOOwmu/zpORnQBN4kL3Sk+Z7R5/XRTI+Rp4Kz6c5joOQucvTTRA0yOKmPK3QZmz4+7tY1f+VORQg+CRYJIh2GXq9Ip8nI2kCS2F9KeU20n2LL0mRQeQF0IUR094bYKaDcqMkLepZIPvD6dHMwcDOgxJYxeeTaLeyMYd8Awf7EUuING5JTTPAhZgG++zF7YTqGVr7AgmlJlPKnXq7U+P3Gs70ErwFyqM1+4IHgkiEQry8c0EFLM+hsI3YzlMu/xCgAnl483q6xf1IQtPTFCE3oH+6zylIBVDBN4MwQklvuf4c2/Ra3VNAEXOWHAJu8enRZGszW4Xmvn5PJ0M3NlEUOCKMey4nONrt2CTqBEa6lmo9
