---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgArrTi0Itd3EwxyjCYZwyAPajMdPhtSnptuDmPhmEL+betp7p4xFU8L4di4xsUYT9aO2swweuN/YghCdapHz1OiX3sMrqT/FGnaxZtOeaDAssKhj0wpTgAtuplLLHg1bKIupw35NNhuwyT8cNw32UkW58yWRtEfCdB6GwiDmC07ks26n5im0cMb7HJFWPAEn5M4Mjq4LK0jqy7KM72YipN6gz1EmpOCkbjcyx+RbehO6pa9THR8ZJQu6Uc5T3Ga5o/mPjLgWfOgWa+ICiR8RdFZAeDB2BP63taU/Pxyjz5wVSes8dVPgsmVXuXtYUSDI9yRNisVztsknq64V99MDv6Vid79YW/U2vUs3d5TXjEJxnQxh5nIxs+nmqE0ZUH3+/W+1gCk31+8RrXDt2SFXz/KM1FQdEv4gz9S7v1Nb6SmGD6DWflvQyYHO9oP2iPur7/eEUJAxi3qGY4okxNI0PxPMo6vKntMNEvcuP83Ck2AN3lTbRGFGS4xxTxdqmjugsHn0jIAJBxuBQKAKpKb9C47dkHaKKeAmQVMBs5OlBMeKt/OWgoI+xFkpGVFdyK6C1f7v4sh8HzCSVMw2snHh1ss8RwJ9HaEIZ0y47R0ANRNGN/nGBurqcomVtxIU5WGNjq3cNsB28aLffJLWrl0BZHlcTna7UKxilNGna5rPMf/reCbyfaNGBef/HQOc1r2RXLvypV9pzc4ICCTo1SmyTvrhePQjoWwW2bEDbguLfR15KzdFDG5Kpbk3DA26Ln7X1A5UWZcRfBUIYRisimdLDUeVrZ7WUYnA9ryih1BFL55B8F9n6HwPQiRvfePyKilsxeVjnJoEuj8efqc78RSf5BcYlLK8VWnYeDKmx3MKZ5kd3f5lQIqn6N9YYCM1C37KH0zRnp2xmeWBjTAMvYsP3t1jk9E3/R9ag==
