---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCFkWorzOodnQ7xS0rwxUVn6O+LfU2ekXImK1Jz+I0FzsbA62WKA4O1Y/CmgO3P/EyuVUXw+k1cHx5mp3MP/zD9suCOH2DXoh5NtADyrU7RgBr41d+7WQ5RepGOy5r88r2BPCNteG2WbanpUKy4YaaWxOT+jHeEe4Z/dcmhCs00ynfnWCcSC7EUpbw8SmntdNtIBuFBVws0FOijMZ4ZdjkMIvlIgvc7iaNsK5ZlBUThPhgsTXPMAFpg0SvbDZc3Fkh0DW8hKX+wCz2UsmyBqY9DWU46dWsSvyyXHInUPK9GIglc0aEsfKIPXEET8YZCtCae5ze8jsa/UTz/F/dhibwKyiTNLNbta/XQBzi614f8x6HQ1zJDfA8hgT0hn2/lO5ZEcgV6svhmFqf9Ne7qG+xVCck1YQCrLTnhbbLC/QR471GTsVCW57sw6dkG5q7r5xEvNtD4yb1gspBr/fPH67YuHR/r+bq4ePjjvV5FVhv/a8n/zuJ8xJ1FSzWfZ92ZV+NixCyn8/3waoNbyVcagmQhPYCoL75sYZW3Z7Bnef679zM4UXpALzlYIm4IxkoaKYm2jwE8A+Eqiexa613ErSgJQua6AVOsIqwrY7MlKll12EIi3tOvRYRxwBqXA1QB42NBNTleWDJu5UtgRQe+u2gRyrRIcuh4mpT9djgetThuMVbMkgNsPEtYzU4x2iW+etcULjDoD2AC0KdldlLUq7VG5JBBp8ceNI/VWzQBqBbhodQsoX4ed/xwV/NSkBb0i6mkfATbuk9wibuzvF172SWinbKufjUppWaKxB6ql6P+F0LQyVKXJWSVawsBzODQiUdoo/idK241wcSgL2we84x6F+uyFyaiKHkftI4Vlo9NTNxDuao2gdH1yY+qQ0G0eBBCOc1rR+p6G+THA+ER6mABmFZzJ1ZmYA==
