apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBDxZFN5gb11P31E2snk8u5izuTyLKRog9GUX5bO8i3AZ0Mu8ByhLfPuIQkOb0FvdD12H2udU/aJaRlrapJVV2Tk1Kh+qM9eFyZ48+Y5t8zrxvnDzi0o+/5+qeIUNyPafwuQ7UhHkM4hsL/jYB+pfIrgH4i4Oh6+1hkT2IcGH+fZ44Kze0UO//xOuJ5KmfdPk6GN+9Q0KAZca5/UBWipBkxShskpmiZljASGO35/IMjld3ocNSYFXCx6gF/CeAi9DHh4+Fd6am4PIesPWm0uu7k+nzHsAUiE5K3N5GYHMxJScGQQMmZCeU/29PuzARE8+AtF3j/2AWlYKzDqu739cuR4MTQbSm01bDGMOFJD5M7zg4No3PiTrluMFb569hdn3cWUxf6q9ks2+myLiv/YF7HEUeI96pfEcxiah3DapOQo5R20DaVvwi17I62hFh3Zc55739mTrMGuoRgBfiZMsNIKSMwfNp8x/JjpHJrKuOd1UsgEQVsloVoiwczXRzA5Vi9m4nD3aepPprFe+0mYd4I0tNPTwxSAqcvl55qnllshWVbSEIaa+HaH1DswRX3oG74/8mVwuyz79JIG29h6ICH1hDksqe6hC1FkZN/G5HMamzsyAY0jw75ZL1m8VEAlGgfNGmcrFBDkbngx3lbaFm0bEVBu9kZLrRvy3XHjC9SHD5PFLrt9NovSYl5H8+Aed2yAoTGi+ghoCFbs6BBHGmHW6w5GAqcIBgtvpJv+qbyyvZ5ZD9wSnM7YHJxtrN5GwJCHCU3ePqCp/O+mzGSUIPw2iK4cbUyDX11wY99GOZVp/h7/nQOpM50xKdfuhrm25EYW75Xk3Z2Bx2qxbOzfCFbPR9YmpzJv3DvFXXamNfdA0D/LkZIsuRNaNbcmL9zzy4soibryxB6+I5ijxHi+pEy5qPk
