---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCus9nLYF8ZCG4xHHUkes7Mo3BNWtZYVejr5LHyADOld9VljELXmvtla/h3fFqzpJTZOocGGZj/XaaOkq3XF2UGKS4EIBitkrnzN4qeeimv5eiuUZAh5eSUQjPecWwj7N+5VnUHdo/Xc2N5XCiE1GOp8uJ0LwIwBK8zV7NKo6cUA+4g86T2tSNOSfvjYnS+4dLl8zG8+sP8omSII0GsH0l2Ydy834V0UAOcxs64pHZN9UX45owh/yc6I665v82UADCsLA4nx+dueaNSaZiFJmMhdNkxWdMFiUmNZeH529jd+cLTd1vb/hrPFXyn4WpZ2onDQjWpF1cPws51d8JTMxQ01vaHR8qOe8uIMat1vymQwC8SBce+Vpi+3gGz+sZsezjyHq1L0z8ZCnJWJBt/AVOYa306t3IzkhriIre5JNlyU3skdBz0MD/23O+QFti+9R9nGvJXXQDWtu4IfUhJdAZvZ+KvUVaNOKEeJMuc1v/u7M2e8zCwi31KaP+53PD8YEqF4JAPjdg6NHXG6Lph2HGoiobPNnvnDDIxh32e/WwRS6r3S3jXZz0V4zZGtE7Q1PnUOQ0Q/T5LhTkmOvbSRVIqtATIIOPDe6iDVPBYFr7Zl7ffMtmrOL1lr3LLwRsag7RQa6JKVv2O9comgt1GR+dpbm7UczMjS3q8crnagvpqI00Jq2BR8CxGl2CWDl14tXoeJfnO6QCWi+H7mUb5cZqnvgu2cgZrolNzdBCOKler4bfyLGipgItbMxrxJMi62owWSxhTn51HQXMrThE0A/z6Ve0tApRUgTp50AeEpcN9DHGjEXgr+gEdcTz0Om1HEx3m53AX80cwk/TogDUYiawIGnK6DEV89HkyMDBJnlelm0KnkL2KCLnlL8jfeBIns+CHe2edWtOgZgVmCpu1DX4lJS+bGDG5Mw==
