---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBd0oJB9iNTxcr/RomlLA8YzqzFJrIXlmVOTHEurJOow64hdk08LRijaFErRd+LWdctF7yBn79K0K1+bX9YuNiZ49Ckjt8n4/imBJFSxBFNt8QoKhIwJmmnP216yyxqwEtdaxKEgGl883syKpDFjxRQYTk2Bs3L4VRPdVSIidRMmooSD/5hVfzTo+Lk96xxKQAD2uFsRUv29poUhVg3FeVztOtdOqzkBCz2miX0+5oK9bK9nixv2cuwh67O49Pwa18vrZyxWYO/6N14cdcl06DS57Y73eowe5KFdvWhNMZHC7BhmusSkYCy6U4PVm2J+65uTNLtqdgYidWI0CTtc2dn26UrMjFidf2QFxk4HZLAP0yVxI+13DY9zyWQ6THokjV6V27uSa8X510yunfNULjup518rYhM+qSrHr/Ar10ew4icAXaa9SUptfZBQJAdscBEvYv6sftWwEXu/7918JNeqDdjxdd5cszbwB7zJNpZb7GEVzKnEZBG1ALkrhvCMpXPhMcpWccpc+bHnPL7t6K1eiNor6+MeJtwk4upOXGNVam2Y4Zxo+7xijMv0Fdm4Wob/3LIiriPc3h2GgBXIJ01uPigwhoSi9lyCR8npW0fol0m3mpBNhOuicfbGQbfYJ0/OhHOEoh98XW/qSXoXxK+5xKjI+JKvFOatAiJoe+2YMdwBMOElChpr5n6KjGkxJp3JdHBmjR14gevZ2AlkAzmKTCzhcUAjW8uU9GHRLOQ6V3aFb6oz/8rW4kofXD83QbrouVYoZRX2CYz7nv1/t4Wv6Elh7K7/fgWUXkgR8JJAE/uXF9JNw8sUUPdJDzOglpQo0iFzky5pEbAw2qCpIIDLvTy+u/zyb5sokl/KnoWNuhI0bxjzxnIusQdriIOuDtBDvDG0ypneeU8Tt+/vmc7Ml2RuJP0+A==
