---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgBe8oicYopIhAEfjkf4t5tZccFuO2LVsmAnIiaL+PqIPkR5WJ0V70ln5xe1gk4Nyn6N3Jcs9SUTe6oT0WYDOYY92Yb1Ni5v0BEgVR0RWGzeSuRyTSTp7R0bfagMSX56lGQ25WLuof+wb2150G3j75bZknpktOcdnzwO7ImRqEpfjranz6SnJkLhE9x4AZ+TSk1Yv3wUo4qqApjhrTiullgOXgKgFSR30SJw5c/xEh2wKB565UqXRoY79GSGjpZjRT8OQNfngY23Ig2G0cR6dMkFKon0VY6vavsL/SzDu+X3GF+0lTzubvgoUMWRbZXuGT20WVvYqe1Fis8q3Mq6s6iLgMBgZppFyPfOA9+zqwKiPgd2DaAAEg54Hp4FzcUjWbH/mhRkhTUdyzjsdZqsUo24h8DsBCVypspq877+hboPQElTI/H0ZRKl/BTYxjZSFOx1+40FsbiNOOtJqq1kyewWH7keaoegrBwqkJ2vKPr7fcWL2GIcOjMtMblyzgwRhxSqRjYj/40d3Cjcv+2H6+5fligams3h9n1UMGGDvTtULmotWXZ7Yir9CiRqh7AQ9rRiWL/qJJAk5l78eNvcIk+7RszzbRpqyklxEc7ARJV+6Rco5brHCYPXwAYj3Cdyd8EnyJ09SvCxu+gLC8o9h6xJH6dxJ8mX885aGQ+2Nn88QRpQ/00iYWFRXR+eo38PP2v5o7L+YCch2W7D13/nvIPeIAMaDznOvcr7LwBiETAeCpwmjDG1GsBW3u+TlOsi0pLeQqfph9jKGbIbNzXKMEJr2VQTrpRUYrZGmgE1HlOqbT5/wuksWey540xyVJEeL6nWjg5tLRmczYDWGCwm34w9557ElFcG6P34s2LZ68iyuPngBxktmqzx5Z1Wj90cIsN/w0OagPycbikrl4FKPx2WAMzy3j5gMw==
