apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCorX+49wOHP0GlcdhYOJlK+va/SrU6k0sb+pTjA7d0N7Md+gw0eESEYaSkMMb1dMWDtn/Iz49thGG9ej7vZS5E5h8itaFgFnhi/MFpUqPQsyoAp1J4T/aOfeGM3ZPDQffNFYMwf2+73ASwpUo86vVZMVVXN3bQE0ugASH0xb0OxWf19405v/D43hQokM71Y4ckcOX1FGdo2ULrCDDfwkVxOXcnfaZRqsXLLs+e2v4jgz0ppOv2vVGjiGk1XPWmzyXCfOQOtcKovr3Fy0OLSncv2SIUrJkhL6TllyfYrUPDLGMlFHAv92ugN5FPoyZI+EoDtAn+IgDgEqc6n2FD+DWYJtt/2BjEWvc+qLV9ODxbVClLfvrh+rVWF1dY7piG7vzoMj5pF49bIHWdCfZBtU5L39mYOZeX+BZI3Q+BgzCJ0RTdt4dElVtWv9antp5dbNN6RawicSxo4TdG2DlInIngf+qW1oFEtnUIoSrYR5gFD+9a1MpHmfi07ehaxqXXPFvDH8RgJFtH4NbS+eVJB6QOwwT6o0SQW5mXy1btFA4bDE07zkCK2Zxy24zqD+bLxyS9UlOFBjx+BEk3bWmwYeZN7MLtQfLr7YAJxp1ecwPYvAkb3IpuBQR1hXsn1cFEfVl99HdP6KQz0EP4g3+jYrlYWEZYswtmUyl+LLxQFIJr5Ckdd1ZD2z0TFhgW98RWLwRjXEh86CvjVYxpSU9nli6onSLg4kCgbzURYBcr8f7sSVI/fiatCnK+c9Hr3WgH8or3vbLIMSECeaYlosstdy0dZVgio+OGGgELE27TEsMhrVJEu4ba3VB/P0IBXOrS8lyRawrnqGiVgtt4GU15UEPby24904ch+OxQcqumBXcDd/PB6SM7VpqejZ93g4saVAbgk09Rjk1PcchczD8gtcNNxnrC
