---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgA6ZY4tCrhQxd5DwKg+Qzd98i1nVutyQ5GeCvTY4kOL6I0ksjTqJt2uiP4z2sd5z1IRWfKsHG2/+r6bpQNl3J4XsFQSRS9Sdxv+u00s6AfUgX1KwanXenunY7nrbwUjW0MLS5Z3fFir3kO/y9ZVyUvrNQvEG/Pf+iF2ni5XTD1kCk1uY/CIwPow4DrPj7AxWUERyH65EUymchXNXjDDAdHZUV/39lTKiH58Zx9bSGav7/jlLPxSOz9HvuoSm0kT3c39+S5amoxzwp30oLTH3ilX4DVoEMTEm9sS+4eDVPvBxGl9aoZEmBfDieb6z1iHhUO9eEygBkuxWfH3gGUQEFiRlatNUAmgrUUtSSiWZ5/76pj2TEnD4/mf6ooEXPkFEUTs1x3eVrVoDzMZrNQNVKxLda7mRn6COjNBPS+0zJn7Q3FlIzjgp4ahHa4ep3zeNl6AvNivW3eNIyDwdf4lLaEQN8OCSPr7eJYoCiKLU4Cln83KusQYgbp7UUVGF1GByTmK1vyK4f3sAAEF7+qhLeKKGGMQQRk/FWcfBQiR3SsJn5Inodq4OJjOwQLZZBgFnfx/mNNXCKjh5LKzJwpg2mgpebW5OodqeciSLkYLA72/p21bzXjdSEgrgA7p9i5V0bvnq6v8faYrmcKyK2hX+dS8iGMoJ+qPkBsWPcBKe/u0Ffynp0leEadhM60kdDjvdc7Q0UtpM4ElArwMfYKCUb59ceBuGgnogHZI3twSGD8TfV2mHfQVv2rStTpAzP8NXWaM4ZslZUcvjJXT7ZcJSkvXl7PkVVupPivdixeeBXLuovpa/Aj2fEBZtR4MLZwcfQu3ONUvJrScjbssOURY6QMOMKWqxrgsBW11RofAWYKTFHTcUy/4ZJfQ74XsrXf/qOB7130AskPlSVNOGF6IvVd0RP3fWAprWQ==
