---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAcbUgwPvsrQUJQKT8eRZ2WsE9vpKeP4RrvShCPsOEGNmiMu3Md0Yl17iHw6wRSMIdGSd8x1Ksa3Co9KK3wZS2LilwrcapewMEWDGPzTET+NJSfLEXvBsIIltnzMuYX3/tb85mYJqzAx5Nzuy0Meh/YxDT/wjkMoe4Wcj/HKuX7rw6mYDQe6rTcWf9LzByf4+gJvfdTEnc5VQCrUeptVHFUyQ/RSFdfAWkNoPqDMdq5a3ZNUe10jIqSDMoD58+5vb6sHwsHEbALGIfBiUgu/31wGBWX++sfG92q5p8KsufbemA10Om8mZ6hIy8B/XbwKCpeqtX+slLETa3q2sDu3TIJb6Lo7eHNqQRRQPMwoGTGAosJ3aI3sb1+yzXpyWsoO1t8VSN0I21xR3vCVz1cc4KwQPcj2X8HuM4zhvfGl5XH4tu2ATqDOoplnH1nbXHUAwKXcB5qm4NJG3fcJCxCq5OTW+jsBPDnrFofa1LpP50BfpTMZdIFLEIDr+lhR1S6jdz50570vdx/6m+SnucE77lrYWOxfu14v/XX6fJMbJ54CZZrElVaQIQvTwTukUCOWFCuViTHtJ0H8HdosFwSIlm6AmqGlfI527H7c5g1ZN7OazdA1aRP4vIk8i/SC6OBM/3zLFoCI7mPBLYDEz42E6X52OuMdD1Iv1WwIa/W+glU0m/+qe5ZEzZf8ThcII1Faz80vKGJamK1XCokFGG19Z4vvcCCP4JsLejvILW66dKT/kTLf4O7l7ehbpu9Wzl0aE8kuqHk5ZqNmu/1mxMH4g4Cykp0/Or1/IMqKnWpzyZd7gBwHyQVWVmXc+IAYuvfHaVzFSQenYZHHoyEcCEnIRDDw3pXSFm3yclYYHii6IYcDEFUY+C2a1wDSpk3LNIFPbecakXT3+8yXcVWl3eR5BQO5SQ0QxgG0g==
