---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCDieWG4hbVFBSbka4bSlhxbdJs1UGWqf94CT4yjMUW3pe+6a/xvbF8WDxbAQdsdBWcx9LToWu3J2S8sII8Rmmno3U8DONkIkQj0Fb3bo+zcsGpcU41ZA5fCNy/o7iCxen/f2ZAQgqm2W67okhI2OBMpvzC9kjlTQC9AeqWhKjmblcBBayFz3CvG47wsouGiAMqwWLo1L4mLsx3WODtgOye0Dt3YrUa/4CoghMLevivFlZih9tvrxA6sKppQOHVWGk/UeL4zZheU2s8xqWwG/dS9DbiunhEjyLyhbC2eamM0iL3cMxgUQIqCp8xu3UGfDLjrQRlvE0yVpufLf1Nn/L6dd6fcZOxVo2X3daACcyf1wCsgJZUNp0+IO3Hq6+d1G0Lb60/j9MioYhzRxW/bIJo/afI/XZKb2hZj7rvdhc36r8YinjomP9bFYUWalB0PTIabek6S2BVL6v0ugXP3W4pmblPO4F8t2puOiz5ldD46AUdtmYjxuGzKO71aOpmIjwYUya4u+/h0dpQ6vyXDs5V7/Z9ryiZmygK7b99KUURMwQa+U70hAVQizRUS/cSt5XTX0bxTXF668BT03FQK9djFelKMQ3J0vhmUoG7IaZQoYvTzdSW3Y7O5RsPHGEh9AFbSpT8kFx8kjI4SoHCP+QtJsr1HyDG06Dx+blQeqgWgOaiNDSfBhNRcrHMbRRW4nDSk1yaGRkCoVkhJxCK441CMbMMGKrxEsF6CPiANXkmKkE7zXhrpsdifHFmzxx0shmmFn3VqONQH2mMYqw+ULjjgW8GQo/i9QPFvN2PYwMmTWKscpvO+DKebrKuRVYZCIOurwvcx2QY/NB3lWXmdjSGbYA57nZdhln2lp24472sdpg8zMED+qGyJbqbAUcyP2rQXXu4iO2qJZj2dpqhLr18tcHScIG3sA==
