---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAh4gvF5axJP5/s4WQEBbpZbJRsFqifOCDZnb6+sKMb52C/hIdmfVkadpvkbIFeNzXE1gnHKMTT1keTuLfLAvEJ9ciGqpyYlK02qPxEUSje7KMBwj/rWwOYMr5va5V5x8ybaJarc1S6qIWY/GJTBZYiVwL1YLmw8xlNDDqePucP4nTQ3Pa10Yp4XgBABrPL1v6gcmiSDdu9aHnliqdDO1uSeqOAkW1Mr3zT3ACpuI2ogevDI67s4KTlXePr5Um7E6RoN8YYjKBnyP1u7mEDBvJK/4RPvtJRw5VvLY1K/m/aDClIs+8cIRilremE4skzlTd2Ldl22tGvJTjrs8988YjS/w55wRc0zlM5GvF5zdgJXFBbvIPbHPyC09gk6ZPO8anMEeE6cz6xqKnnZMGQUga4nW4IgytH9b7phl1guG3MmeE2b5YOLQsMkxcNqDFRW6C/sRclcSHxht+u600wLP6sVWNQ7m2d/6x++1TY3nV5y20nUnMxiU0pKDGglup5xC7oLY9TYHYN37Ms87OQ7VbO1MaaInsWQh0r1AQE00IIXY6iwnFbOor0NAuoyhp6oSb3B9GdVJUImVYj4d0ov9ELOeC18WpM8nkeIczWk8ebfYkciPcl+4u2oz+CW4Y54PzxmzFNoUqiVADBxqXYBpokrpiN5PMSsUWRimny/ptmvM8YNIyUzQEaafyAPzEyCkxE22GnFuSCnwzHryoYF43TVscZWG8o8lmkjSOhKRxdhgmu1Yjw93TK6+5ZEhoitRYRzlkRbgSkKiMFl24R/Mhiio9b/FgmeqUNqHb41FdaYgqrSIPMgGBMD5SZCQwKafnDTnDJWrSAGMO+JhFZ2A8jw0v3SHWEW60QUEpqPKkzcevUJQjFUdmGx1A2GFnnHF9AbvPxoWRq/PNFPRmxgwpB51K7MHiSDw==
