---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-stack-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgCFIkdwIc/rH/mualizctg/K9+x3Lz07xtwy0n0beLkK16PZaPjid/58uxUYkFf/wTEEiSDi+D0Etum/UboHWNxu/06F0xcQ0q+/nNRV5DGrv7fWg26q2j0bpxl/Yy8E0GwYIMhvFuDSfeRGb6kwsRUanO5+1o4cHnhkcZTCjhqHfR/qt4NcQUYARw9Pju/afVQPNF3v/sYnvwiN8QARtDaYPRI3Cqf8A5oVCFODF+v1ami2UnFWsZi4gImP+nzYYezUg5qnwy/+NGEKKRb9dFJLNozaGvvQFVM0vUb2wSEeou7cj6qiBmLOFu6/CSSM5+lXv/+R3oqcgK5/4dK2olIC+bo40dOfepWJ4b8ruZL9HSXW47/NnK8fWZeJKmWBydqz/E+OtW6P7Milz1NkxHGDQI9EzLZ+Ll8YpK9zIJUJ/qH6onOAn7r3kLoJdTHNg/sh/HdUVjf/jZuOC60Bo3qiJ0SFlH18hrESBwYBaDUsQtysPsyQpGKpdE3cwT9jVGSzPCDwzf9nLBWOCM97oUdyB9W1WRuUAdEMQt+hXBGOqpY/XXCqExnkDNNRYeDlhs/7M+jvdn80kd/bTfO0dbkravCR/P+6eg+c2T5KSnyvOb0IlpqwpFEvfKuySu0A4JGqbv5xkT8aA41BygYheAn220zay9GhLnERYdIcdCEE9w845gmNqouF6zUh8kRt4KfXsanFEu5Pwh0RLfFA4/llWNRggUsZjTFXc9INMEAb5YXagBnjeqXErjy9fwphIXQ+nhArcpbrS6fjc+KLNPcFWmmTJuvS2XL0FPW/95OCRGmK5R6wZlzIWk0UirsD62gWQpRSfoDEg9NcZXjhk1w2bz2ieqeGA34AaGqpLGBmQeNm7MARp9h7nh8Jbf/uKxku7t+L/F6xmZIM5eOAAbCAa3cEr36/g==
