---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: vector
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    role: Stateless-Aggregator
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "4000m"
    image:
      repository: timberio/vector
      tag: 0.27.1-alpine
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      #
      # Sources
      #
      sources:
        vector_logs:
          type: internal_logs
        vector_metrics:
          type: internal_metrics
        kubernetes_logs:
          type: vector
          address: 0.0.0.0:6010
          version: "2"
        journal_logs:
          type: vector
          address: 0.0.0.0:6000
          version: "2"
      #
      # Transformations
      #
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |-
            # Delete file label from log event
            del(.file)
            # Standardize 'app' index
            .app = .kubernetes.pod_labels."app.kubernetes.io/name" || .kubernetes.pod_labels.app || .kubernetes.pod_labels."k8s-app" || .kubernetes.pod_name
      #
      # Sinks
      #
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki-write:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: accept
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs_remap
          endpoint: http://loki-write:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ .app }}`}}
            container_name: >-
              {{`{{ kubernetes.container_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
    podMonitor:
      enabled: true
      jobLabel: vector-aggregator
      port: prometheus-sink
