---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: vector
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: loki
      namespace: monitoring
  values:
    role: Stateless-Aggregator
    image:
      repository: timberio/vector
      tag: 0.23.0-debian
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      # Sources
      sources:
        journal_logs:
          address: 0.0.0.0:6000
          type: vector
          version: "2"
        kubernetes_logs:
          address: 0.0.0.0:6010
          type: vector
          version: "2"
      #
      # Transformations
      #
      transforms:
        kubernetes_logs_remap:
          type: remap
          inputs:
            - kubernetes_logs
          source: |
            # Standardize 'app' index
            .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || .pod_name
      #
      # Sinks
      #
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ custom_app_name }}`}}
            container_name: >-
              {{`{{ kubernetes.container_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
    podMonitor:
      enabled: true
      jobLabel: vector-aggregator
      port: prometheus-sink
    service:
      enabled: true
      type: LoadBalancer
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Service
              name: vector-aggregator
            patch:
              - op: add
                path: /spec/externalIPs
                value:
                  - "${SECRET_SVC_SYSLOG_ADDRESS}"
