#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      containers:
        - image: thomseddon/traefik-forward-auth:2-arm64
          name: traefik-forward-auth
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "300m"
              memory: "150Mi"
          ports:
            - containerPort: 4181
              protocol: TCP
          env:
            # - name: CONFIG
            #   value: "/config"
            - name: WHITELIST
              value: "marcos.soutullo91@gmail.com,marcossoutullo91@gmail.com,marcossoutullo@gmail.com,marcos.soutullo@gmail.com,kitos9112@gmail.com"
            - name: COOKIE_DOMAIN
              value: "uk.msrpi.com"
            - name: AUTH_HOST
              value: "auth.uk.msrpi.com"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_FORMAT
              value: pretty
            - name: PROVIDERS_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: google-client-id
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: google-client-secret
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: secret
          volumeMounts:
            - name: configs
              mountPath: /config
              subPath: traefik-forward-auth.ini
      volumes:
        # - name: configs
        #   configMap:
        #     name: configs
        - name: traefik-forward-auth-secrets
          secret:
            secretName: traefik-forward-auth-secrets
