apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app: traefik-forward-auth

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml

#
# Configs
#
configMapGenerator:
  - name: configs
    files:
      - configs/traefik-forward-auth.ini

#
# Secrets
#
secretGenerator:
  - name: traefik-forward-auth-secrets
    env: secrets/traefik-forward-auth.env
