---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: tools
spec:
  chart:
    spec:
      chart: ./charts/kah-common
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: flux-cluster
        namespace: flux-system
  interval: 5m
  values:
    args:
      - server
      - /data
      - "--console-address"
      - ":9001"
    env:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_UPDATE: "off"
      TZ: Europe/London
    envFrom:
      - secretRef:
          name: minio
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-11-17T23-20-09Z
    nameOverride: minio
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: minio-s3
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: minio
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 100Mi
    service:
      main:
        enabled: true
        ports:
          api:
            enabled: true
            port: 9000
          http:
            enabled: true
            port: 9001
    nodeSelector:
      node_locality: "internal"
      kubernetes.io/arch: "amd64"
    tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
        tolerationSeconds: 15
