---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "thanos-${SECRET_DOMAIN/./-}"
  namespace: home
spec:
  secretName: "thanos-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER}
    kind: ClusterIssuer
  commonName: "thanos.${SECRET_DOMAIN}"
  dnsNames:
    - "thanos.${SECRET_DOMAIN}"
