---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chart:
    spec:
      chart: thanos
      version: 11.1.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: minio
      namespace: tools
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    bucketweb:
      enabled: true
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    compactor:
      enabled: true
      persistence:
        enabled: false
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      retentionResolutionRaw: 15d
      retentionResolution5m: 90d
      retentionResolution1h: 2y
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    existingObjstoreSecret: thanos-objstore
    image:
      registry: public.ecr.aws
      repository: bitnami/thanos
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    query:
      dnsDiscovery:
        sidecarsNamespace: monitoring
        sidecarsService: prometheus-thanos-discovery
      enabled: true
      replicaLabels:
        - replica
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    queryFrontend:
      enabled: false
    ruler:
      enabled: false
    storegateway:
      enabled: true
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          memory: 500Mi
      persistence:
        enabled: true
        storageClass: longhorn
        size: 12Gi
