---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  chart:
    spec:
      chart: thanos
      version: 11.5.10
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 5m
  dependsOn:
    - name: minio
      namespace: tools
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    image:
      registry: public.ecr.aws
    existingObjstoreSecret: thanos-objstore
    # Enabled sub-components
    bucketweb:
      enabled: true
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    compactor:
      enabled: true
      persistence:
        enabled: false
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      retentionResolutionRaw: 30d
      retentionResolution5m: 30d
      retentionResolution1h: 2y
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
    query:
      enabled: true
      replicaCount: 2
      dnsDiscovery:
        sidecarsNamespace: monitoring
        sidecarsService: prometheus-thanos-discovery
      replicaLabels:
        - replica
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetMemory: 75
    storegateway:
      enabled: true
      nodeSelector:
        node_locality: internal
        kubernetes.io/arch: amd64
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          memory: 2048Mi
      persistence:
        storageClass: longhorn
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    # Disabled sub-components
    queryFrontend:
      enabled: false
    ruler:
      enabled: false
