---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb.git
  ref:
    # renovate: registryUrl=https://github.com/metallb/metallb.git chart=connect
    tag: v0.13.5
  ignore: |
    # exclude all but the CDRs
    /*
    # path to crds
    !/charts/metallb/charts/crds/templates/crds.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: metallb-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgpadvertisements.metallb.io
