---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: sources
    - name: crds
    - name: config
  path: ./cluster/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
