---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      version: 9.20.1
  interval: 5m
  values:
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.hostname=${SECRET_DOMAIN}"
    deployment:
      enabled: true
      replicas: 3
    experimental:
      plugins:
        enabled: true
    globalArguments:
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    ingressClass:
      enabled: true
      fallbackApiVersion: v1
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: fals
    service:
      spec:
        externalTrafficPolicy: Cluster
        loadBalancerIP: "${SETTING_SVC_TRAEFIK_ADDRESS}"
    logs:
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep
            names:
              X-Forwarded-User: keep
      general:
        format: json
        level: INFO
    pilot:
      enabled: true
      token: ${SECRET_TRAEFIK_PILOT_TOKEN}
    ports:
      traefik:
        port: 9000

      metrics:
        port: 8082
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: default
    resources:
      limits:
        cpu: 500m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
    podSecurityPolicy:
      enabled: true
    tlsOptions:
      default:
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
        curvePreferences:
          - CurveP521
          - CurveP384
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
