apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-env
  namespace: kube-system
spec:
  encryptedData:
    CF_API_EMAIL: AgBcdXciQ7mltjhOfZCcFYDnofrD4t56ybaYFLovDLp7hwTXIron5pS5Rkf/g2N9WyO3fnj18Xb4hb7Z3A1aspfJwJACRTwm+sX0mmHh7cDloXgdvh9qrJmDO6LEj1VQ7ZzBfvqCJd8FmEXYGIfnOPmXcIODeNSCk1gxIG22H7OCIf0Di4/Gax7gwpCyLF/bS5BR3fcqn8wheZecFJSUdrSXLeLWK/VgzY8oZW7sIYqZZFeV4WGFQftjsky8uWtk+ZkSV8KMcOcitoGFt05ZK5gnEuObylXF5v4lw8Mk+zY3Dm0luP5qX2IoJZo+cs3/ERrgzVYF0g0kuT6fXqmuurcZPPTG4nrHnNuy362VX6UHBz9t3k4mgnQ7BClaeO/6oVkLYvJUn0yWaKJHMBr+AUASgwvQjMrKU/lXCQ61nZQazJiYpqVim2SIngKBfPGYGXllqnOY1IBzjDX0nvw98hB+Nog2Y3g+ShxFVof1PQbpOIwcrukBzGMLCMMORCpn3RNYlS7CwagTcTcQ81UKgm8UmI8h3Q0Z9AB/bPOADYHVFxCDx6MX/d2WrmwoZ2E9AwZEtBIfGK8zLzi18wyDdpYmi6AZXfAjjwgh6dctJ+n7iol95z9b8Rwld2mtlBdIh8FT+g95yU8aLaAIPqNUDfhvrY37XPHbLuztsonDUKMgCyJavyMfGGehbJtTTjOJPTfAVjqj1bwbamkl7dUXy7Jy6Z5X5fW4tj63z/c=
    CF_API_KEY: AgADadAVGm6RFQZzb31aBSVSxIjlzE4oiO3/75WUS3v6T1y7fkyAwvdbIRFLfNw5IapTvwA6CIlML6HoRDyxcjsfDPwI3K6WTRWP91v93YeR1rbo/I+ubEVZXh8KhvMw9/lifI82Xt7Ch3cLj3V8425lDt/67BMVFfUFyuFHTLyIxdmVzjePixVN5m0B3260syVvLtl7i10yJGjqhIXw7xP6jT/OiF2zQU62jfunPD2IVb8ZSjEhBWfQN+D4cfMG5qjOiRDufXjqacpLsTGv8a4Ic3TdbIxD24frCyl0W6TBZ8R5ZulXECf09JkkxzZVYEJUMmn61nKtV8MM6Wx/rsmI7oaGrPtp9gLH+ySCjxqx74EOYaWs8LK+OEc3Ngr9fqAgF/rUAuOv3rRcoV8ccmpRYDJslkaYHfqqcYUV9m87IgI1Bi1QqCwlTbRdTMKneDAK3QUKiDQqI6x81GVVwsvHlnf+hZ4LawnGaoxrsDC1x/9fxoWiwekDP+wGw/aTnZN8p/9hst21ia+wFn6qATBoBuZC8Q8hvBSDe3qFH2T2iwvG5k95nSnD/pr7LxGrW/KHo3NBG4gZNl2UKve3AGoo0OyF58SqRx6TKfBOvxUZ/zB7sOCFd+7ozoi/ZNYpqXOPqwMxJ6dqGb8XO04rsV44Si6s8gxC0jn2YayMSFBMIZng7A2GT2qGjjtA9ThTJ1dKSZ/ssDUqR1y0wNfSUtAAkJoPN6O7b52dWmKTbGzWRu+z3cds
  template:
    metadata:
      creationTimestamp: null
      name: traefik-env
      namespace: kube-system
