---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: portainer-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://portainer.github.io/k8s/
  timeout: 3m
