---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "minio-${SECRET_DOMAIN/./-}"
spec:
  secretName: "minio-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "minio.${SECRET_DOMAIN}"
  dnsNames:
    - "minio.${SECRET_DOMAIN}"
    - "s3.{SECRET_DOMAIN}"
