---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: vector
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: vector-aggregator
      namespace: monitoring
  values:
    image:
      repository: timberio/vector
      tag: 0.28.0-alpine
    role: Agent
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
        address: "[::]:8686"
        playground: false
      # Sources
      sources:
        journal_logs:
          type: journald
          journal_directory: /var/log/journal
        kubernetes_logs:
          type: kubernetes_logs
          glob_minimum_cooldown_ms: 5000
          auto_partial_merge: true
        host_metrics:
          filesystem:
            devices:
              excludes: [binfmt_misc]
            filesystems:
              excludes: [binfmt_misc]
            mountPoints:
              excludes: ["*/proc/sys/fs/binfmt_misc"]
          type: host_metrics
        internal_metrics:
          type: internal_metrics
      # Sinks
      sinks:
        loki_kubernetes_sink:
          type: vector
          inputs:
            - kubernetes_logs
          address: vector-aggregator:6010
          version: "2"
        loki_journal_sink:
          type: vector
          inputs:
            - journal_logs
          address: vector-aggregator:6000
          version: "2"
        prom_exporter:
          type: prometheus_exporter
          inputs:
            - host_metrics
            - internal_metrics
          address: "[::]:9090"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "1024Mi"
        cpu: "6000m"
    service:
      enabled: false
    podMonitor:
      enabled: true
      jobLabel: vector-agent
      port: prometheus-sink
    securityContext:
      privileged: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
