---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  targetNamespace: postgres
  releaseName: postgres-operator
  interval: 10m
  chart:
    spec:
      chart: ./helm/install
      sourceRef:
        kind: GitRepository
        name: postgres-operator
        namespace: flux-system
  values: {}
