---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: flux-system
spec:
  interval: 20m
  url: https://1password.github.io/connect-helm-charts
  timeout: 3m
