---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx-charts
  namespace: flux-system
spec:
  interval: 20m
  url: https://kubernetes.github.io/ingress-nginx
  timeout: 3m
