---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kured-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://kubereboot.github.io/charts
  timeout: 3m
