---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - blakeshome-charts.yaml
  - coredns-charts.yaml
  - bjw-charts.yaml
  - deliveryhero-charts.yaml
  - grafana-charts.yaml
  - infracloudio-charts.yaml
  - ingress-nginx-charts.yaml
  - jaeger-charts.yaml
  - jetstack-charts.yaml
  - hashicorp-charts.yaml
  - influxdata-charts.yaml
  - k8s-at-home-charts.yaml
  - kasten-charts.yaml
  - fairwinds-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - kubernetes-dashboard-charts.yaml
  - longhorn-charts.yaml
  - lwolf-charts.yaml
  - minio-charts.yaml
  - metallb-charts.yaml
  - cronitor-charts.yaml
  - metrics-server-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - node-feature-discovery-charts.yaml
  - portainer-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - sealed-secrets-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vernemq-charts.yaml
  - victoriametrics-charts.yaml
  - kured-charts.yaml
  - vmware-tanzu-charts.yaml
  - 1password-charts.yaml
  - vector-charts.yaml
  - kyverno-charts.yaml
  - descheduler-charts.yaml
  - aqua-charts.yaml
