---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets-charts
  namespace: flux-system
spec:
  interval: 20m
  url: https://bitnami-labs.github.io/sealed-secrets/
  timeout: 3m
