---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vernemq-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://vernemq.github.io/docker-vernemq
  timeout: 3m
