---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics-charts
  namespace: flux-system
spec:
  interval: 20m
  url: https://victoriametrics.github.io/helm-charts/
  timeout: 3m
