---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      defaultClass: true
      defaultFsType: ext4
      defaultClassReplicaCount: 2
      # reclaimPolicy: Delete
      # recurringJobSelector:
      #   enable: false
      #   jobList: []
      # backingImage:
      #   enable: false
      #   name: ~
      #   dataSourceType: ~
      #   dataSourceParameters: ~
      #   expectedChecksum: ~
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: "200%"
      storageMinimalAvailablePercentage: "25%"
      upgradeChecker: false
      defaultReplicaCount: 2
      backupstorePollInterval: 500
      priorityClass: high-priority
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: false
      replicaZoneSoftAntiAffinity: false
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      volumeAttachmentRecoveryPolicy: "wait"
      mkfsExt4Parameters: -O ^64bit,^metadata_csum
      replicaReplenishmentWaitInterval: 300
      allowVolumeCreationWithDegradedAvailability: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      guaranteedEngineManagerCPU: 8
      guaranteedReplicaManagerCPU: 8

    # BEST PRACTICES - https://longhorn.io/docs/1.2.3/best-practices/

    # Minimum Recommended Hardware (https://longhorn.io/docs/1.2.3/best-practices/#minimum-recommended-hardware) ✅
    # Software (https://longhorn.io/docs/1.2.3/best-practices/#software) ✅
    # Node and Disk Setup (https://longhorn.io/docs/1.2.3/best-practices/#node-and-disk-setup) ✅
    # Deploying Workloads (https://longhorn.io/docs/1.2.3/best-practices/#deploying-workloads) ✅
    # Volume Maintenance (https://longhorn.io/docs/1.2.3/best-practices/#volume-maintenance) ✅
    # Guaranteed Instance Manager CPU ✅
    # StorageClass (https://longhorn.io/docs/1.2.3/best-practices/#storageclass) ✅
    # Scheduling Settings (https://longhorn.io/docs/1.2.3/best-practices/#scheduling-settings) ❌
    longhornManager:
      priorityClass: "system-node-critical"
    longhornDriver:
      priorityClass: "system-node-critical"
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    ingress:
      enabled: false
      ingressClassName: traefik
    longhornUI:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "250m"
        memory: "500Mi"
