---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1m
  upgrade:
    force: true
    remediation:
      retries: 3
  values:
    # TODO: Delete `enablePDP: false` after Longhorn v1.4.0 goes out
    image:
      longhorn:
        manager:
          repository: kitos9112/longhorn-manager
          tag: 1.4.0-multi
        snapshotter:
          repository: longhornio/csi-snapshotter
          tag: v5.0.1
    enablePSP: false
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    longhornManager:
      priorityClass: system-node-critical
    csi:
      kubeletRootDir: /var/lib/kubelet
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupTarget: s3://${SECRET_AWS_S3_BUCKET_NAME}@<eu-west-1/
      backupTargetCredentialSecret: longhorn-s3-aws-creds #gitleaks:allow
      createDefaultDiskLabeledNodes: true
      replicaSoftAntiAffinity: false
      upgradeChecker: false
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      allowVolumeCreationWithDegradedAvailability: true
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      volumeAttachmentRecoveryPolicy: "wait"
      replicaReplenishmentWaitInterval: 300

    # BEST PRACTICES - https://longhorn.io/docs/1.3.1/best-practices/

    # Minimum Recommended Hardware (https://longhorn.io/docs/1.3.1/best-practices/#minimum-recommended-hardware) ✅
    # Software (https://longhorn.io/docs/1.3.1/best-practices/#software) ✅
    # Node and Disk Setup (https://longhorn.io/docs/1.3.1/best-practices/#node-and-disk-setup) ✅
    # Deploying Workloads (https://longhorn.io/docs/1.3.1/best-practices/#deploying-workloads) ✅
    # Volume Maintenance (https://longhorn.io/docs/1.3.1/best-practices/#volume-maintenance) ✅
    # Guaranteed Instance Manager CPU ✅
    # StorageClass (https://longhorn.io/docs/1.3.1/best-practices/#storageclass) ✅
    # Scheduling Settings (https://longhorn.io/docs/1.3.1/best-practices/#scheduling-settings) ❌
    longhornDriver:
      priorityClass: system-node-critical
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    ingress:
      enabled: false
    longhornUI:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "2500m"
        memory: "500Mi"
