---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    csi:
      kubeletRootDir: /var/lib/kubelet
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      replicaSoftAntiAffinity: false
      upgradeChecker: false
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      allowVolumeCreationWithDegradedAvailability: true
      #priorityClass: system-node-critical
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      volumeAttachmentRecoveryPolicy: "wait"
      replicaReplenishmentWaitInterval: 300

    # BEST PRACTICES - https://longhorn.io/docs/1.2.3/best-practices/

    # Minimum Recommended Hardware (https://longhorn.io/docs/1.2.3/best-practices/#minimum-recommended-hardware) ✅
    # Software (https://longhorn.io/docs/1.2.3/best-practices/#software) ✅
    # Node and Disk Setup (https://longhorn.io/docs/1.2.3/best-practices/#node-and-disk-setup) ✅
    # Deploying Workloads (https://longhorn.io/docs/1.2.3/best-practices/#deploying-workloads) ✅
    # Volume Maintenance (https://longhorn.io/docs/1.2.3/best-practices/#volume-maintenance) ✅
    # Guaranteed Instance Manager CPU ✅
    # StorageClass (https://longhorn.io/docs/1.2.3/best-practices/#storageclass) ✅
    # Scheduling Settings (https://longhorn.io/docs/1.2.3/best-practices/#scheduling-settings) ❌
    longhornDriver:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    ingress:
      enabled: false
    longhornUI:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          # Evict pods from the node if the node becomes unreachable after this toleration timer expires.
          tolerationSeconds: 15
    resources:
      requests:
        cpu: "50m"
        memory: "50Mi"
      limits:
        cpu: "2500m"
        memory: "500Mi"
