---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 1m
  values:
    persistence:
      defaultClassReplicaCount: 3
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      backupTarget: ~
      backupTargetCredentialSecret: ~
      allowRecurringJobWhileVolumeDetached: ~
      createDefaultDiskLabeledNodes: ~
      defaultDataPath: ~
      defaultDataLocality: ~
      replicaSoftAntiAffinity: ~
      storageOverProvisioningPercentage: "200%"
      storageMinimalAvailablePercentage: "25%"
      upgradeChecker: ~
      defaultReplicaCount: ~
      defaultLonghornStaticStorageClass: ~
      backupstorePollInterval: ~
      taintToleration: ~
      systemManagedComponentsNodeSelector: ~
      priorityClass: ~
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode:
      replicaZoneSoftAntiAffinity: ~
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      allowNodeDrainWithLastHealthyReplica: ~
      mkfsExt4Parameters: ~
      disableReplicaRebuild: ~
      replicaReplenishmentWaitInterval: 300
      disableRevisionCounter: ~
      systemManagedPodsImagePullPolicy: ~
      allowVolumeCreationWithDegradedAvailability: ~
      autoCleanupSystemGeneratedSnapshot: ~
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      backingImageCleanupWaitInterval: ~
      guaranteedEngineManagerCPU: ~
      guaranteedReplicaManagerCPU: ~
