---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - helm-release.yaml
  - volume-snapshot-class.yaml
  - ingress-route.yaml
  - certificate.yaml
  - service-monitor.yaml
  - prometheus-rules.yaml
