---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-default-backup
  namespace: longhorn-system
spec:
  cron: "0 1 * * *"
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 3
  labels:
    storageClass: longhorn-home
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: weekly-default-backup
  namespace: longhorn-system
spec:
  cron: "0 6 * * 6"
  task: backup
  groups:
    - default
  retain: 4
  concurrency: 3
  labels:
    storageClass: longhorn-home
