kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-civo
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  nodeSelector: "civo"
  dataLocality: "best-effort"
  fsType: "ext4"
