kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-hyper-converged
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  nodeSelector: "civo, cloud"
  dataLocality: "best-effort"
  fsType: "ext4"
