---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cronitor
spec:
  interval: 5m
  chart:
    spec:
      chart: cronitor-kubernetes
      version: 0.4.7
      sourceRef:
        kind: HelmRepository
        name: cronitor-charts
        namespace: flux-system
  values:
    credentials:
      secretName: cronitor-secret
    config:
      sentryEnabled: false
      defaultEnvironment: "Production"
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
