---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zalando-postgres-operator
spec:
  targetNamespace: postgres
  releaseName: zalando-postgres-operator
  interval: 10m
  chart:
    spec:
      chart: ./charts/postgres-operator
      sourceRef:
        kind: GitRepository
        name: zalando-postgres-operator
        namespace: flux-system
  values:
    configGeneral:
      enable_crd_registration: false
    configKubernetes:
      enable_cross_namespace_secret: true
      secret_name_template: "{username}.{cluster}.credentials"
      enable_pod_antiaffinity: true
      enable_pod_disruption_budget: true
    nodeSelector:
      kubernetes.io/arch: amd64
    podPriorityClassName: "postgres-database-critical"
