---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - kube-prometheus-stack
  #- jaeger
  - loki
  - influxdb
  - thanos
  - cronitor-heartbeat
  # TODO: Revisit Node Problem Detector once all their CRITICAL Vulnerabilities are fixed
  # - node-problem-detector
  - vector
