---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - botkube
  - grafana
  - kube-prometheus-stack
  - loki
  - dashboard
  - influxdb
  - thanos
  - speedtest-exporter
  - cronitor-heartbeat
  - vector
