---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - botkube
  - kube-prometheus-stack
  - loki
  - influxdb
  - karma
  - thanos
  - speedtest-exporter
  - cronitor-heartbeat
  - node-problem-detector
  - vector
