---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - botkube
  - grafana
  - kube-prometheus-stack
  - loki
  # - snmp-exporter
  # - speedtest-exporter
  # - unifi-poller
  # - uptimerobot-heartbeat
