# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:StUTSaSocQ3+9bNHKNwJv6h1HEyHUjrwQj4lTlmT9R421Ow3Hw==,iv:igrNQce/li36788a++R737S9w5BXlBqIeXw6Djp+xdg=,tag:DdteYxjXpQuC+V2pPhN4oA==,type:str]

