---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: monitoring
  name: cronitor-heartbeat
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            botkube.io/disable: "true"
        spec:
          restartPolicy: Never
          containers:
            - name: cronitor-heartbeat
              image: ghcr.io/k8s-at-home/kubectl:v1.21.3
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: cronitor-heartbeat-url
              command:
                - "/bin/sh"
                - "/app/cronitor-heartbeat.sh"
              volumeMounts:
                - name: cronitor-heartbeat
                  mountPath: /app/cronitor-heartbeat.sh
                  subPath: cronitor-heartbeat.sh
                  readOnly: true
          volumes:
            - name: cronitor-heartbeat
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: cronitor-heartbeat
                      items:
                        - key: cronitor-heartbeat.sh
                          path: cronitor-heartbeat.sh
