---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCO2dAGBmZILUL4fSGgokjf44ImTdS/m+2+ixx6Mulwl2q959RazjTKx6jOIO5jOxc80rS9Q9f7+Vd19I5fHGyfhHtalDV70OMrealh41JpxCdv+CvzK8y1jpphrkblWifF9NWA1rFdB302U9/mr5/NSkmZx79OlFgGDSlrxKtVCQdVxFUYCh0/y0DrlAiBSuUxQzmGVuhqK8B30Teyb2wiu5iLAIYXkKj4m8sG2HwCwvyzp+OzsmOrnz3a8XYDYHhXHyD+7yENBGMzAKrw1Osty/U0oYSJe2MfUJUUoeD46HMEGLZzoKXMpC8lBUk91zuwCfskWNTm63Q58GFF37vWLiHQ4BBfN763B2eBPHgjM6UTXfOR33S8M3Y71ehveZkRVwK+MPFaEX3U3/eatxMhvI6jpLhtZNeYZar9hYL79P2R9R5uLzE6dabUIayuJVu+VohhPLnbVhXEsq1esTEjPaEN2uILUY67ePcGujddJ/QHbrh4OaKa+F2R87AGE6H2vWO2fQMIKi65bJOCo2KPdWyxUu0qvisvARuH8vVbF8hWCQL473+WNv/0ysluXc0wX/vrZOCSAlVx7/Z464/Lw5cBb9W2KJOszG125LpLpc6MhNqnFkIUPzEHElouSG7frfJeJARJ4gjixAkgTrt2jWe4QbbNY72F+HE16B7mPVLXzhfePvbwtrpbCh9dBTu6szE4NgMafR8QTgCWppMoEvBpFnnxX+bpHCUdk1F1sHBsP1Ilc8wKwkiYbgm9r43yFSFI6Wo+Su3ggcM9xb+FuX5RQu9T
