---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgAGkd56/bNcUbk5TfunkHZMG0qNjKrunHbmvUir9J2jZpqyx9QyFGwROMcCNLcc+/7FSwst7G0rCjFMxENkygR4x1LNH6TkhEIwQAgkWAlKm2NIJZZCUCfwhpA7vo1JEgJfN25fm+w0NQI8ah+QFtIUEnDYFZl6sA6ythnv+mJZMdaBpkDQI6pWSNpnhlC6gZtYIvVJGBjxzMkWUOS21gAYwmTMOL7YWmmu6SxxYCCRv/IEtJuB/RVK+G+DDXux0XFsnf79K1JIVHHS6T3r1N+27P3xhtacPyW3Pz/sydccA43cisB+kod0F+BUWqfLJmzVCbh8tEsPmL3M6m3c8HobcJNFsXcCNq1uRLWwey6JRyNMMDHZWX0v9B/N85DcgPh/DdCkZS/Q/7sKIE95A11z6NoSKfe0NkIbF5r4jEoVDc2rHQP4xNz/XrC2hMvaqpkOm51SkQ2rGye3MggEKlSVTefjt9NnFsV1hA+Vz8UdSEFTXRBAqYc67jVYVorD2HIKzZ1B9mnvxJHHq471fGfaAcoYstkOOo5VS4YZp+2d8iI5IVfzrpB8ROQqhYtgnEW6rOZKhZFuuAEE5ai24U3SPqxiEDNERD+TKc4Wowq01P/Ai8W5gIeMdfFGd7HEluvOgCbbcyaXGy9bFy1XWK8cxh0FbGlteqFaqw4GII5+RWlqzuv56XTb011dxwo6qfKxahrnQf54BoR0wYuTh29fb2CIkruec2icODPz1kUAP4z7CEXA7buykKWkJz+uXZwVspz4RsguqCBG2NiiQx8RkITbY4J4
