apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCujruvNLwcIdI2nrXiN+zwyZORTWHIZJgpef0U4LOPfIPZph+MF8OlNxwDmWQcB/YHJ50k+XCMI0pR6kPg3IXmxEWlF8GA6lSNhdLR4p5PPyDkTW9fbRH55/XwkdS0XRsm+aNM178DTCYQ9xS9o3db+M7RysT9amlPCGK9PgZkOtMdECbbj+ttf4a6yVJ+nSEiJNxDN47e2WLkkwB9ob64SKqfPohrfRiVXK2hAkPlm2szmglD31vMB/iiWdBxHRo3yFYP3qj148M6V7N8Uj1jd1OX4y/Y9hvHGHf5MkYSdZ8n1S/eu1IBpX124E18+LMv+waft5tfAZL3h+KmnbvwuNvaraksdqjD9f5mR0Qaf5iv/CwUWk3QihplFGGToanyzXcso0+/lfglY9sKVLzgjzaGRdXQY01ALRlpcjyaD5DOYHiP4cmXeRkoweBAPBJOlruccu29ON36c6h/AcYozi0aDSWI27M66folx2/6QGzDWM30po0AEo41K4Nt5rUu4XCG5sgpoO0TuW3RF/LFNKiUzAnWSpKZyjXEuCXkO3HQ5Tx3ynxKcJLjbrieGLLTNcktLzMfpE0B2nizHN5GIW8bS8dHCQCMhZ1E/McvhljdWaBYOBwfEnjaqWywWPbY59EAs5A1ol0AnuWws9v/kDoZoaF1dES17/wgeAXKO3Sj8H1Je2en1Xvnor3AuPLgdcgr6Eg1VzzqvsLvtmlwQZ2h4rDYznze4xO2l4wO//6I7Ozrk6zeqm1XOsSFWV+hzFdI1EpCz6YwTBOWO1O/z7tPyWNk
