---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCthBC/BGgvk6s5X6bFThRkySmzsKKCB+Fsrq0Aqkl5EV0fH4SzNK+x8qXUab6RsQK/G639zM6iEh2bnx2DBFXngl4Qg2zwfq+ExEDDG1Y753omI8d9FgB39ZN8HLX6q0NaHPP2dU4c8cllpTr6fYSAh/mE5hHEk1oIPcJL1fMPa0vFVzIrXyVqjxtqSJCz7x6bxpu5lCQCsgv6cCrZmqcjaReB37yt2MltVnEhUclnbS2X54e1bGvp89UOBaQSxfAraIqrrq4iOS9abPU3rVMIN79LADiMwSTMOs5nSwZl/x2OLVYRdNOah8v9PzO1JHzE3AUpnrycDPTJe8nnNM3qHuIW5WiEh1/vplJ84yOS740HtrsaqO8cDplYHqbQB3QKsgUz2RzrV1J2gLdamwe+ewC7nyysu5iw4snbgj1H7yl387Xh1gPs14QWSx33K0FjqkDxRru1ORM8FxRKBh2fADhmDyrSUZI1e8u96qmS+RkfvXLCx6UhiqnC+NzQNUZcaj+E+c9TvJHKwONkS9rIHBjYz+SEIEHDTJI7FKBySOmsN7tgf9O3pui8tONuA6bQSscGvRZn8xBgDhuxa8pdHGx/+T1R0Q/gprteMxjFrOrTotjgbqfwa/T+hIKsL6eJe8/1b4HaC5Ky/HENr+VVWOJz5bzIEB3AO7gJ7fHKEbMzqJyi2Mb5OSJJtGHzC+ZvJLI73WeGMv+eWqHsGNBkxCJX+G9hrhcodcCi0FWTSRHaKNNPm31fg453zUYxoqhvyL9tsIq66yZ5AW+xSKh/vmzCD9fA
