---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgBxznudPDCqGkVj+Osxjmswwoy3cJ+dg3jY5U4lqnPeQMOWFKyynFqeeymg0P6ZHND6BvPGGGu9PKwqr7Vv3HuqvUYCdLatAR0bXE98O7BSqIQsixd+OIjvzldwrilXQhXxDMtGqZYmwjbuBaQX8a4YhC8xgsNF93J+z3tFb9DUNNBd8sFB/HYzHnKiY3ESbdRhEm75GhLB2+HwOauc7+hpaqw5lwuLw4xsm3m+0yreg6/272frfjiX9ceyKZGqXUpwCAaxfiTVgcSPezG4KQd004AKoTb0zYT3H/1dsaLnCbFEdEo2yEFD5CvOPwzw/hNyzY7ZE3m+1b7yS3aYNjPBsp3ZFwZ1M0Mx32LxSJ5l9e1upxWiIp9sd/HehBVfu6o3ra2gsreQl8yd7eaJqykhLpL0AqM0kEF3xzgLcAZvbh8RaFhZXLOKvruQyfcPhpJSnulW04oey1fN0DeYrDh8Hi+q6goel0yyebOrNCSmhQsOTNiKSPXO3gT13iBZDkLWA7GLzoSlFLUNgxa+xQpBU+QuMnb+C87qBsupqtJco+aZkUfwYYQxZ297FdUJMEM2CBslNLeJgIg4YNUohcRum9zRTGkmsu/2hg4lkYVt5eBNGIJGayf1PJ9lM3B6rlp0yC4chD0WXWhT/xosfoi1MIQ3gFex6lLsdb6qnjS3HEdtetUtEE2JAvxz/rCnsLQ7/l0zizte3dT98OjxdA3Ipy0BQMkG1q0wrZRScLj8IGYQpBoDpfVif7PjpxfM4XUAJcFBrj84EGMU+1ECw5Azd320DlqL
