---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCkJy+UQlYV9OreRQOtTNmRMMs4FGZkoB93Wn8YObjv48wdVQxKeuPDrgZhQ4+iqw/3htWx4Nho5r/Agae+v2q4wiw6Q0MdyGvNv6W2KNvF+pq6jMsGR6A1nv7Q5sxWsGnob3HilOjOb0riEQ+DUoikbOk70QmOc2gL91ifFrQEVwnIjG9eBzyQVVp/5k1c+tiNxfOTWPhB5GeitO+BbvPLUg4sYP/Wv795icX4JI7GAhdd609gAILbnWTXPoBH04M/5LLeJ+ipMcglvc8u/sf7jVHoyBSTI6NWDih4Pnn8uQmWn0JrxbjESroZoGjF0wNvQG/XV1x53XKj3aqjA+AsWLOLDxuYNlmq+1fN0apbO+VPs2Avfh9ybhDvQfeiXDW7h31Z8y/36O27Ihx6urjcLKH1h8hVpiLuuyAXz+C74I5Yw6+ISDp+NpYlCoDZ1hpt5H1pf8qIrfx2DiRj5ntAeuIiqeLqkYVjvMYXrrQpLe13Ffww5xhs5EZAq2gDTYSt4/nTWH0kMVvJbBub1qh13iNJjMJ+zqI5BdDjXFRPyTW9AaVpnXaNVcw2+DX1kFiROWLIwmxpgHwwH1UoAcIKQaZtxNHSVqaHVkxF4o8bJ4I6fo22mGuM1GOM1zWvQHq7UOtqxpvBvoklcXLF0KvL63xqCjdNLWDMeItsosu6NWJvfNG9UejvElrCHS+P/7EFcSqZt88AtY2F8CUaqJ4UbxHgk1XdfuhHgI30WKQdVihK8m7hdqf41/rsKV2xsH7VnPMf/rkYTwaTUj0xEI8vXG9mH9+V
