---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgAqrozXFbX+GaIhFsEJ43UnlhI82zyaWh5YoL4T1wjfDOaCPsahC2/CWHJiywpTp/f9Qd4ldL0lzNVeYIYF0xW06IUhO/rLU2GqkyQrYlkR1mG0AVhWLOGvqRmfWtOFusHCH3W1U3gbg9yrtWNDkD4ukdahc75LU4bLPz6bXBE74xO5Q8bzAXEOufzizo5S9XLTCo+KgMn0JoDm2kYZO9TgClaWpM/CDCoK9Sf2NrASJzDHlxu35KY9QZIMWOFCDst2N/bPNgSZRWiWO64J6RHW76oRh5rmF4OlXX384PZGtFQ0+iyTLpbiJ5vjLUj/qvy8iYsim6O0sogI5ub0Lk72arLhvrkzUQQf4I+dQt8JIt0zXpv2QvPoabAnyzu/RNSATiMjomVS/K1pdytboOH62FhcpA6QcDAIw7zImVT2WKNbAO7+9S6q0Sy0cGCHflwQGDrvCHeasNGjLtEhCBI0u5sjlr9lDwNzEJv2SeUyj7qFKRsJxNpT7decyeQbBPHyHWRpqMc/sS8K84oU+R1MDXY9BQY9q6MZZppZrTlX9819GllElVKzsA2KcAQDDmiRJZIuC7bwidBXBaexfymtvsrlh804Rb4RPmo4l6RLelMY+xrdnU3IlIqbLZ2pMHbVPKOoryO1WzA9DGmPPTDwOXbfpXUZ0WquMul8ZzzJThJEE/DVVuFWni89DqYsadJhmzgTBXhD5Cges97XjEfMeGCT38FfQ3btxGqaSr5Fztim/lJWmgkxQdziL9F6YjoVC/YWfxo7WSagimnxtBi/Mplhe80u
