---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgA0tpyaCpAmPN5HRdnzXmMCACrJs7lxbkZjntfMkpWZGDphhYTPhm7jI68ASE+bNDfOLEL4vJHUeefnDe1ChVd5lm6/dAoqrFukA1qkeKyPx5efxLNEv3LEPkA0FMiuzN7pux35V2zERVuSUCFXCTmCZ8XEZGqq0Tc3RPjPuxv/TLXKB1+yXc6zgTYSEV9/t9hTGMSbX/hHxwXwI7IYpHpHxHovWs+EFv8XPjIbrZtHFVzjbghh6G53Vc29rh9+Lj1wb4QBrRi4sZk2pfXXvG8CjTfKe4px35txBZEsqCMtqa8jX8CWxjAt/leLTa3tjuW6GK8ZIEXdo+YFYktdPivBNseqkG9S4ib6DxTRuNbo94nF9D7NyprPDdmJQUBwI3uOjSz66OUnv7xILQgh77zbHo3lMhMFzJ0hfW+5FKtJUM8ig4/rHUEu1fXl9I50gX4IwOFBAR/KHJrdbxz7oCbiOH9kc9p2GMPGiiWFex6fTQViDKIt7Nclb3zc1ZXQ7oyGWcrk1EHxEQLKAND/5zk/+uuH2Qk+u8AEiHc1qfWrk2vEjfbettzZiV+5ArYmE6XtOQw7kEactl5NhG+T9e0oqHf/OMpUmwvr/dL2Nvh0ghbqo8KmosuszERc78dOBExaqidJpWVYjcG6WwhOcxxz0YFg61qdJgVWf8fmvevOKAKy4xBEO2Fx/ZGZ72ZsCyq6mNyiFcasX4dFP+rFWBVx6ABYhWDItiGkgPYH3ORgum8O4KjDPPGJQOk8Wr+/iF1zEKlN6lLGKPybv+bf9QpfyFYU5Qq+
