---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgBxclesZuU0Z8nr91abmK893xfHSqAkDetQoHWP469exldTpfa8PhhStlNPhMwqQaCTZueQQ4skybKEQc4zRLjSdZLVyY9vt/viPXbIZEHwEmjXo7xFL5k6moYAMdMSmVtGTwxuKzfBBSkahCwjE4n/UKwiOxS0RF8F/jqcseU4U6o4k0LWjUoa9uPl83yuAaaLPIqHmBWP4b/5gO0r8GUmZyBJcuglgbAuKbn3LYRdGAFeMVA2jvkv8lhsU8hUBqqGgqQ6ssU47WoS2d649jWMunjmCoD9o4tT0MUrdFr4h+JnWacNaEy47yb0Fof7V8VVh++Jz5O8HErxx0H+aFmjscedlwLcGsyEw7dr+YQYbOeOMgmTBN8qy3TXfePONCGrkSN5kAnUbeFzJF5/5RBC7/tH0FmP3tQRE+BK6XYiPnPGkre8mIU/0cJZAxxotskDZNFs1WjBO3H8SoeCk7rusF+S6VgVfdhAPtPfJ8ZIlkQNhu56+o3XEFnkJPgeKDICogzvBHgXQ4fFentzRd+37X3aQFs64oUfbwTKBAzw24Iy3m+EIdsOVeUeR3FFvMo0bCTjT8xcMstUEcF4Wk9v39RQ8Um5u6CsDBMoZbH7498k/YwMWQ4Ynr6J7N48yypoyz84RYkNmBG6o5bSVLDSqn1FpOrkmm36ZwkhF4OvHgSqyExhs2fb7i8Om4q62AGg42A+XaUBfXe1INkMcvYoRv0kTjMqHvEQPacN2ukfftBhSBK611kNufVqw8AsINUWNEAASvdl5PGxHHQnijktOxwtvPB/
