---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCfUub+FvMYR9UVHaeEnwfI4+EBO6PW9rdKWX0GQj5Tldb/KPiqzKLK/exw2tZuOnShIL5d8SDqIEVJY/Moh30T/a5RR9efe2FV6VgCHdFnTqyf4e6BJW1hyyBzTAgzeynxc4X08GUQEm9YevspUU6QtoCC1Qm17IYmfPNkXj6s+LdEarN7SffFIe/U4Z1sycsYoFRmpub9SLW6Ol5j6bOAh8UAsS737EGGYFWhtTcCHO84Ma9+3mcWJQUgjXYFwmiPmEr2VmvWw1AmEGHqOXNgn6VALy0ut2QGTHTYdXBrMKOUierccTzf8MDt1/c4JzpOaHBGnIwtvs4qn8SXdSr2tm2PZL+1MLjoSaEM2CprcrlEueCwE6vGxB86s9Ro8uqCVt+O5Iu47n4B44bG8RYUlqlGShElfaikmlwEZsiNNpTahZUZxo7gOcnYHFKX5+BHm+KPpLMroa5qs0qdhNZvpjdWgVEuVFodP1xgpRPeCjukNL3ypf6O+kL8tyRnm1dK3PNvI7datBEthEIMTcmdXWYuqYF8+9bJ9G5PxTNy2S3B4oCccCdZb2+mIutPjw7VHE039TaFlyhTIoP1j1dbDO1RhTjr+Ftk7nqoZ4x0ecQxePQRs9YsX1R0Rbzg9j3/CIbsm7KKnbHXcUOVnUTVnqLySvzu1dSW+2k5Ft0cxOyW6jOW53sALzzu2UHqFpUsGdIcK7yiMurCZ9RrvbNCqk9xEF9+HpIrx1Rm7XksChsT5H1MeR85O/5ohsrI+7cTD0nsy+Q0DCCHuuOb5g9iTM+FPzI9
