apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCQ/hCg/ZwcQmrKPO+chxt/Xp/6FtzMf/xP4DV8dW1wy4puCRS9HLdETMYsYCWKelhJt5BgYusiakYNpOo7E9Gb5E8WrPRYf/nzomuUtfhRqfj7yzySzjrh9aTAikW0KKyUSI61Efn4BjPK0LcBhEZGwVjsMpT0mQvbUF105hbcGmlSYr1JW011aS/LBrpkc0VHPUILPGz/biIX7PNW6T8JFcmsZhtwlpnEQ1QhnAvUMd8ZneDKEWvPdJpKI8l1X7s/xZYZbwf6sVaF0LwddAyiV0Q8AHF6vxbF9jjYHfZRdO27crmC3D3DmUM+P6VmpvZ0p37aCcPdn7lj86w98qz9/TRvANxliAOvanuli+8EIHp5Mki4G5z4BHJE9LuufX0hYBbFv50mBfic2zBnbRCf3tf2YbG6LSi4WM6TRDYlOa0k+60dC2igGCLQvHyHaBTOWZCJyazz9SSwe4Mu00EQela1oFz8ziFHpT3/4j4bePQYRrixo801DI9bhOzcyva63RS4Q0TE5FptJ6agHt6dhPSfG9w7aplsZMzfK49MQt9E1eWI9w0Hsn2kThOmbWOjqiKYJUr2Z7wP0kNPMw9ADUzjb+hu+kalOkc9nGWAWoBAjEHx4veTNxjyo09+NSN9GQwHudkqnnGONKdhvKYwysAsDzIoyb/SsVX2aulVv8DXPiGxRFambhEa4wNqdGXLX0cNpMyEU/71o+cjZguBqWaywWate9fXekEuo2VYM2tv+rbjpWeOuUeyCgcHnzVOjBM4XWQ1Vt8RoO5o5j/GfuSKVAl9
