---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCniH0Y76mFdQiYe5ecZxFVzXrSoNiDj7rdXF40xwo0Pyn+fuV9/A5UJh47k52Jy58qw4Tjl0CO9fbyOBnR76u2fGqU2cPXeC0qHE6gjxTmJSnCoer8WgVVrV7otFdpgFuXCD5Fx0gJBM7ksZsO1/Q7D6yi3dm67t/Xz+7Srez8fGjEFEtWP94tUW35VZwplJlKIG2R/w0Pzn+yipGP4jir0g42a1TsY+8myv8/7rAFSfMUwaF2PHPLii0jwqt/UleuGIkT5MuZ+wbbvWT48Ib/FATH1bKUzcml3HfniUHqBoZEO7ZZ6vSsPGYt3mrWTtsty2Q3/3wEbp0dEEWYQrZD2eqBWabluJq887edKhL5qaT1JKD84TPDm19Jz/fvC6QoQLQAXOaTpDxxbTKXnnt3bBbax6MTtvO47efqOGkCprzndjYRc+xiUVV1ADIy8Q/3mV+W8gbpFKxo2JA4Zr6FpY2bjkDoycPyQuDyFJzwO15pXCvZbTyasvuGMD0KSgbCMF8IxC8sOVVMJAButVYI5phr+zrtfVN9xJJ9xjp5sgbDUA4dJJKIh/qGNpfwNAuH/MgLemJroJ/RGIGdEMSAVloCYvW6o/cDg5vgPIeAeXhF6MihLVMKsMSdHF20eU2Tk1FgJaiSGl/fqr+RWzB0E+mUCLO5xt3/ygkPl04sIbXW0K+wWorEZhYoeTDC1NEakm9ZfG/2jPRNlIsrPIQhxkBmJtgPxiyDs290ljTDM+Iy5w+kwTqtufAGN8/XK/d4HH2h/qaoufZrUIUWCPiQblZCKjyS
