---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgDBAILeWno1UtbV6uWykreM2u11yr4D+URnzpha/Fqnk6stBDr3VaQEiErnjmXUVZX41U0ubdFfBK3vG36pXKNOLq/0wjS3+UFOKhG3rHull4mJR3z8/UlbwJovg7hAxfADJyhxVNEm7pEttvanp/pGoW01BNCsRlVPEgAPExHLLIygOMIpJyHdS2iPT9bnn34Q8SH06onVxOu98inMm710mtUy802C/OhX+JvxVWRhYA0qfzZIz8hTL8S5Y/9MxuFk4maK5ztU9mW/NODpz7UCL7/ls334vgUmgW6vgmQhFwxQX1gqKWttaehysvx3TGZwWsGDJyW6Mqna7rYN6CkQteFb4wyDYByz+LRFlZ+M+W2mfqj78BQyO4M80Fg7c+HHiVsPeAxrylt7IlkuHXbZdCmZJUIjKxuJhWggnOsdG69eQVU/WVULkLVsRkngiEcaD48j+7ob2S9GnwMaGzia13UcJ65ZKKrMWdW2ZqwL+JbBM8gTyyA6aHtQuGUo9/rim8+GiSpRMvPDxbK33D4D29p6UKXivZKCZg+szf5JN+T7GgwxbXqRFAvnyAe5JKAZ+T2wW+AdeuIIiOlhEKdXrH6mcgSW/xA5IgsnVBCRVvFz1+zJ3wIzAs2FRF3UfBaQ3HU6kjWwCGHfUhhidLGINyuz/zhLD5PHVYOPoFYfnKFLTGAfDlsE3UAEzqzEZvCdgEo//8//vSEQjA416n5ZAgRyvS6SeMx52WWIG6uP4Gv8d69zVFyzLx/gjuIxai1wt09FZjQebLJmLaAl1NEOYB41XTWH
