---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgB/g8a1aiVG6WzeAYUvVYZzIwVMqL0T0mQbMQLDkHli8xWjg9Od/vFTI3qTSd+cphYvTSCPB9iI6DBIPivpuqrZqyc2p/wVl2gYFupo8twl+h37kuR9UKZeYixWIav1SDtZC8PfUc4mDTYZpC8vn+8oXh1TuIobrOHFYiucQxBbLWcbiF4xQTm9U0TEDvqNq+dhqtCGdZw92nBZrZJbg7OxSiqRj8KZMEi6231YgMWDb5JsZZrkOxJQiQsWCtIYEhL+C4CX61jS+wpYtWPmmOo3k7hINUyfARQudBk4s8s+ewcfzvBL/19LgOW5iMzNebyRZlWW+RvRXkWuZ3gc4of+J5jwHEP6bRcafQ/GWkcsyH95eKi7px3ugC1WC56VtXa4SIaQQdz5XaDJX5wstWqwkuM8sHMMD8hB9csgbFncLMkEoR71EqX2BUXxKuNt57fZeoqDc9ZUDsowZ4XGqGfPBceqekgeqa29fVwe9nPDYM8LTqG6lFClove6qJeaqMA0i7YnIi2xeANWxawLf415NhrlXpsk4itxDA+eHNJd/UxGRDslqtk84vERqV/+Tc3ovZdgUkIwYphiOZrVz/MzMEc+s56cIuRScjKThfUo2tTVvZOvwQ+V/soHfvJTz058HFJqhzxwMxvkw2vkwLNRl/ASNchVXE+/mxg02K2RLtY0JE3V4pBLVhE8SCv8HUINlhPZd8/+BvkrqvUQ+llwJbppg/aUnKaKTUDg/ppWaAn51++k5DWA+BPgJh1PxRVDIsq7V4UrohB1q9g28Aq2DZda/Fv5
