---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgCR7liGA/0fEE0ORB4Z9leg8AZU5+Yj8JSE7OXL2BBjo/rXFi1ulm7hefGnJBUSnjiSIHr5HOUOokireoRJHobPKSi05YWu5/IeUvhsObYaQh/Sv6wfLp6qWMm6yO95wJfwvcnK5RvgaaF9r4PvsRBS3hFMQZJpTSvg76cHpL5mIQVnyBPC9XGAiWHSiKfDSEjNSn7O1TzVDTiOgaVWRT3Ozrdwt5x2AJIOb7d4reIfgCfOnJQR/AqLN3TdjukPqJQFUPQqTdRIxgDC1njUtpEHAsJTfOijeTh80FZlExLC/0mPhVWBIXXKny355YoJ4JNs12gohSHw3qlgrU8dCTv2t/DnOnHBcbBXNA9NX5xqijP7/xuJtkZcKqaZ/X+ObTDcQEuNg28XtiYJ22F0iKTFeNSgh5lIEHGKexNXqE80qikJoPf4QnuIT+7Ub4DoX8BUcIyNfNy+FH4LmW+Kyf56LaKrjr6eYnYgE9sOcwiO14nNZCgR8Rx+Rhv0eAYNp4Dz/ihPwIsqDJacAXKGETVjE78PJgaA0jwKpvb+FMBrAx2h1HheYW8bLtKsR6CPjloDwXn4UHxfAAaZICPDY3597nOUUcVF0GF9fNjNrLwlayNKHWfL/5UkVXO6wq1p2qqR9WZu7vt3sLQmQnM54wz+ggz8SDqhsNlUEC7CAbgpkJSS2iUQz5sXuhhBnj/VIzLRM3EfE3Xk3LEDHje0Yco1fEVdPz8ktTJ5sVjwRvQqOidbS6E3iNbL15sP7C+hLSzvH2EiwoIv3ssItop9HHcgslrTrV55
