---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgChGyZLKtG8bwFgPi7oLZkkD2ba8Bg40jvLUKQBLk6j9j/xjbybAr4nfCrunT4Y7V5qvIRia7SpUL7Y2h/vPeMgDNUZMYJwoCutGKOu4ZJnhni+tZgog2Rj5YRMn6K5stox7Ojxyy3X8jklEn3SZICQdNi7Q+HsP3wYlp+/B2nX8izstQkTD+YzSGhi1klqe3IJxUJzecZZmq3KcKG3A9gpT0yB0bLvLsJ/R8HQBanLsXY/d8IOdBVvQG29sYpOTEjHqw8t32YdXb2mt+6pG2acEAqDsQKGVCUoeAIXD6xwIpcvRDh4+gIgifqUZgED+QIBW9qfWYZqSl4BvmkDN/n22z1II11EAtSfp2RtBW4xXpLVawAI8UV3uDxX5du/h4RC0PUarL07k843MABaEFXQVOtwJxuNWQINZ11okzZrbhRBsZ2qcSuksF9SjYSxNuUo0LgMwFsSxbQ0AI2i8zU/lIWozlWT3EuyI7uvD4hJtCoM0z4dz+rGVhp7CLINAiUOxhhLE1Mvrt9Ng/5tGOX967xLCSE6U7thxlwSFYlLQ1xC5f1pzsWXyKnzNBCAh8hI9mQaGWr6ehFF+DY9Tn2dzI24A/kYxNdOuCillNlksP9QQpGUnSQltHF+ZE1rexu+h2E46E/qmPS1Oc68sH8n63t2DtsTy6whsXyDynbn3xMkjhqJZfVYEWZAmsFA7yy3dRVQeB7el6Evah6Pgcp1JV5P8ELEuae2JYV5+zH/lEJgL18xk/V4USgcgfyk1xd7lzzJSEsQwO3rvUanbKWH3GfLaKFO
