apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgA/XVJLr+35V1yD9SgSWHCPgGA5mUFdBjt2joM4rbBicyw3rlX1uupJdxUyunOddfGqQC3BNaCASIibgMkQC/xRxq0KqXA/JuALC9gYk85RpesEyX/HQYHv6wT9jXPcQyVdoYqLX+2TxE9w6XOVhLjy52SmgvKJlI1zjxAFb45+NXLFfBFnfWMKhTuEuc1uiI7CBOMYVtigqj4wJM7LmY3/isDZ52TB/nzDE0ESpwoB41Bp4TNKRdoY3G0VMH49SfOZ54vMw8q9k8LuM9osiYmXx3bAus6Mm+boo2ap0nIdN4ELpSokKLXb3ih1rZlq+Vud9LMUjCkAdbDnDfnMBUs4cFV8JThLS+ebiI3pnNU2VmAXrmVp73tW6J3up+s3X4Hg5n4IJ6pggwTGy8fHyGxEGjRISrii9lav7v+69ZRfUMxgVadTtkf6x25fzTSLl1uV2wxfbkRqOZ690kclmJwv4Ji5n8c4Z6773QUyYyK39Jg4OLtX+mGXOuF9b5Ij5TP9zsqdWhglrttTtyQpNqZqnInH6DRwI66PLwywU9B204zl/3v+IRlS5DYh22m1r3QZLyfyaAHexmvc1i7xiFdsw+xbfSqFJD7dWwh0ieLqslxfShRJCYRrv9z/W/dTxh7TwScBl6e/+Qf8sHSammhTdQhiJdy+epXPEOzLkN11b9fmu+K9zBrXL5CuDnDyQbO+sGOkr00srUOb4n0vewCJ844YP+326k0gZCMGs+VuIVqBWSJEribU4g5sf7GB9mObHYs/2JShENJ8t2kj/iNMcK0=
