apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-values
  namespace: minio
spec:
  encryptedData:
    values.yaml: AgAt9LzrvCZoiDrEBRoLkSLq+gS0MuoYPvR/t6xclyOgb0hBkq+3bIP95Uo6Y0hk+EfNs6nxstV2WYphavtVD8MJdXp1rEl7ANFVK5N/I4ov3UesURg585TSAJHDzoeDNdd7AQutOYB4kpEMtcYcFgx3Sc/mp6j9eO/xqs+SlJcv9asSQ41CY17wobhdB4Zl7bTT83I1KlP0WKhPwliWydYehDme2pAAXbK3M9L5Q9sVvgtp7sr2/UbF9Wv9SR/IsbdyTaRQUqp8NXsko/GAkkaINuKx68QSx6r7GSqtufV1Oi/AhHIIVLFisV6Vc8vBDqHwHZnO9CiwxtuzMxQdjW4CMoK9yDCc58oCp2NVc9U6Id3JVqGW6y+3TdL3tOmbdsFigzB/HxWr1wDE7i/A0xjYC9p+bLdmZdVDrMBnNu26q45JXn7vbkM2ENrVG6FNf6fds5b/ZX6Wb15GYdcm59JGu2ygAQKe1MqRmkBYVAZU611kmV/vMdPZiRblKkbSNI0o2xeoezcQcMybAtDviCffzC3nhemTf/OD/HZlAcGLVXqSNQaZQlGHX9r5mmloUusR1QvjX1qUyLJVQP6gqz3W35H41xxJpTcGlwi1jxt30Tf5ee4jlgcZXgMChP2hmpjziEHpvsUfrkv8Ib/4cRUF4jLP9Nwf6E1yFQkbRsqKEP5qcyIhUd0+WDTYu0iOrtYKCTzfir0CaXU8Vnkd3AXstlFAtZp7OMbTo+ONfSSBkKnbxpDB3W0dPVkZ5+mjDhkvdbLBlxmecPkHq1bcbtGUck4=
