---
name: "Create GH issues based on TODO comments"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Github Issue from TODO comments
        uses: alstr/todo-to-issue-action@v4.6
        id: "todo"
        with:
          token: "${{ steps.generate-token.outputs.token }}"
