---
name: lint YAML and Shell

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - next
env:
  # Currently no way to detect automatically
  DEFAULT_BRANCH: main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Lint
        uses: github/super-linter/slim@v7.2.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "${{ env.DEFAULT_BRANCH }}"
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
          VALIDATE_NATURAL_LANGUAGE: false
