---
name: Meta - Labeler

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ steps.generate-token.outputs.token }}"
