name: "Create GH issues based on TODO comments"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Github Issue"
        uses: "alstr/todo-to-issue-action@v4.5"
        id: "todo"
