---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tools.yaml
  - cert-manager.yaml
  - falco-system.yaml
  - flux-system.yaml
  - home.yaml
  - kasten-io.yaml
  - kube-system.yaml
  - longhorn-system.yaml
  - media.yaml
  - monitoring.yaml
  - networking.yaml
  - node-feature-discovery.yaml
  - velero.yaml
