---
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  labels:
    managed-by: flux
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/enabled: "true"
    k10.kasten.io/ignorebackuppolicy: "true"
