---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 1password-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/1Password/connect-helm-charts.git
  ref:
    # renovate: datasource=github-releases depName=1Password/connect-helm-charts
    tag: connect-1.12.0
  ignore: |
    # exclude all but the CDRs
    /*
    # path to crds
    !/charts/connect/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1password-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: 1password-crd-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: onepassworditems.onepassword.com
