---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      peers:
        - peer-address: 10.5.7.1
          peer-asn: 64512
          my-asn: 64512
      address-pools:
        - name: bgp
          protocol: bgp
          addresses:
            - 10.0.6.0/24
          avoid-buggy-ips: true
    prometheusRule:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9.5
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9.5
